/* Generated textbook illustrations, selected explicitly for the argument beside them.
   The same ivory figures work in both themes. Captions carry the exact teaching point. */
const PROB_FIGURES = {
  'c.prob.1.2.1': {asset:'counting', alt:'A choice tree with three first choices and two continuations per choice; ordered and unordered selections.', caption:'Follow each branch to its end. Three first choices, each with two continuations, give six complete outcomes.', steps:{1:'The left panel lists the continuations of each first choice.',3:'Count the six leaves: three groups of two. The picture is a small example of the general m × n rule.'}},
  'c.prob.1.3.1': {asset:'counting', alt:'Ordered positions contrasted with an unordered selection.', caption:'The middle panel keeps track of positions. Swapping two different objects makes a new arrangement.'},
  'c.prob.1.4.1': {asset:'counting', alt:'An unordered selection of two objects from four.', caption:'The right panel shows a selection. The chosen objects matter; their order does not.'},
  'c.prob.2.4.2': {asset:'event-overlap', alt:'Overlapping events A and B: the shared region is counted twice when the event probabilities are added.', caption:'A and B in the picture play the roles of E and F in the formula. Count their shared region once.', steps:{0:'The union contains the whole first circle plus only the part of the second circle outside it.',1:'The second circle splits into the overlap and the outside part. Subtract the overlap to leave the outside part.'}},
  'c.prob.3.2.1': {asset:'conditional-bayes', alt:'Conditioning restricts the sample space to B; a probability tree shows routes through A and its complement.', caption:'Once B is known, ignore everything outside B. Compare the overlap with the whole remaining B region.'},
  'c.prob.3.3.1': {asset:'conditional-bayes', alt:'A tree splits the population into A and not A, then into B and not B.', caption:'To find the chance of B, add the probabilities of both routes that end at B. The tree shows a two-case partition.', steps:{2:'The two highlighted routes are separate ways to reach B, so their probabilities add.',4:'Multiply along each route, then add across the routes ending at B.'}},
  'c.prob.3.3.2': {asset:'conditional-bayes', alt:'A probability tree highlights the two routes to an observed event B.', caption:'Bayes compares the route through A to all routes ending at B. The denominator includes both routes.'},
  'c.prob.5.1.1': {asset:'density', alt:'A density curve, shaded interval probability between a and b, and an increasing cumulative distribution function.', caption:'Height is density. Area between a and b is probability. The CDF collects all area to the left of x.'},
  'c.prob.5.1.2': {asset:'density', alt:'Interval probability is area under a density; a CDF accumulates this area.', caption:'For a very narrow interval, the shaded area is approximately its width times the density height.', steps:{1:'The shaded region illustrates the integral: add the probability area across the interval.'}},
  'c.prob.7.3.1': {asset:'expectation', alt:'Four coin outcomes H T H H become indicator values 1 0 1 1 and add to a count.', caption:'Replace each success by 1 and each failure by 0. Add these indicators to count successes. If each has success chance p, the expected count is 4p, even without independence.', steps:{0:'The first panel turns each yes/no event into a number: 1 for yes, 0 for no.',4:'The final panel adds expected values. In this four-trial example each indicator has mean p, so the expected count is 4p.'}},
  'c.prob.8.3.1': {asset:'limit-theorem', alt:'Skewed individual observations are repeatedly sampled; the standardized sample mean approaches a bell-shaped distribution.', caption:'The normal approximation describes the standardized mean across repeated samples. It does not change the distribution of each observation.'},
  'c.prob.8.3.2': {asset:'limit-theorem', alt:'Repeated sample means approach a normal distribution under the central limit theorem conditions.', caption:'Picture many repeated samples. Each contributes one mean; those means form the distribution used for the approximation.'},
  'c.prob.6.1.2': {asset:'joint-distribution', alt:'A joint probability table with row totals 0.50 and column totals 0.40 and 0.60; conditioning on Y=1 gives probabilities 1/3 and 2/3.', caption:'Add a row to find the chance of that X value. Add a column to find the chance of that Y value. The whole table sums to one.'},
  'c.prob.6.4.1': {asset:'joint-distribution', alt:'The Y=1 column contains masses 0.20 and 0.40, which become 1/3 and 2/3 after dividing by 0.60.', caption:'Given Y=1, keep only that column. Divide each remaining probability by the column total, 0.60, so the new probabilities sum to one.'},
  'c.prob.8.2.1': {asset:'tail-bound', alt:'A nonnegative distribution above threshold a illustrates Markov; tails outside mean plus or minus r illustrate Chebyshev.', caption:'A large tail would force a large average. Chebyshev applies this idea to squared distance from the mean.', steps:{1:'In the left shaded tail X is at least a, so its contribution to the average is at least a times the tail probability.',4:'The average of the indicator is the tail probability. Rearrange the displayed inequality to obtain Markov’s bound.',7:'The right picture has two tails. Both make the squared distance at least r², so Markov bounds their combined probability.'}},
  'c.prob.9.2.1': {asset:'markov-chain', alt:'Dry and Rain states have transition probabilities 0.8, 0.2, 0.4 and 0.6; two routes give a two-day rain chance of 0.28 from Dry.', caption:'Each state has outgoing probabilities adding to one. Starting from Dry, tomorrow is Dry with probability 0.8 and Rain with probability 0.2.'},
  'c.prob.9.2.2': {asset:'markov-chain', alt:'Two routes from Dry to Rain over two days give 0.8 times 0.2 plus 0.2 times 0.6 equals 0.28.', caption:'Multiply along each route, then add the routes. This is the two-state version of the Chapman–Kolmogorov formula.', steps:{3:'The middle day is either Dry or Rain. Those two separate cases cover every route.',5:'The first route contributes 0.8 × 0.2. The second contributes 0.2 × 0.6. Add them to obtain 0.28.'}},
  'c.prob.10.2.1': {asset:'inverse-simulation', alt:'A uniform draw U=0.4 on zero to one maps to X=3.2 on two to five through X=2+3U.', caption:'For Uniform(2,5), the inverse CDF is 2 + 3U. A random draw at 40% of the unit interval lands at 40% of the new interval.', steps:{5:'The input is uniform: the chance that U is below any threshold u between 0 and 1 is u.',6:'For 2 ≤ x ≤ 5, P(2+3U ≤ x) = (x−2)/3. This is exactly the CDF of Uniform(2,5).'}}
};
function probabilityFigure(c, step) {
  const f=PROB_FIGURES[c.id];
  if(!f || (step!=null && !Object.prototype.hasOwnProperty.call(f.steps||{},step))) return null;
  const base=typeof DIAGRAM_BASE==='undefined'?'diagrams/':DIAGRAM_BASE;
  return DOM.el('figure',{class:'fig fig-rendered prob-teaching-figure'},[
    DOM.el('img',{src:base+'teaching/'+f.asset+'.png',alt:f.alt,loading:'lazy',decoding:'async',class:'fig-img'}),
    DOM.el('figcaption',{class:'fig-cap',text:step==null?f.caption:f.steps[step]})
  ]);
}
PROJECT.hooks.rungFig=function(rung,c,i){return probabilityFigure(c,i);};
