import { ModuleSection } from '../types';

export const UNIT_3_1: ModuleSection = {
  id: "sec-3-1",
  title: "Unit 1: The Lorentz Force",
  description: "Magnetic forces on charges and currents.",
  color: "duo-green",
  units: [
    {
      id: "unit-3-1-force",
      title: "Force Law",
      description: "Motion of charges in B-fields.",
      color: "duo-green",
      lessons: [
        {
          id: "lesson-lorentz",
          title: "The Lorentz Force Law",
          description: "Combined electric and magnetic force.",
          icon: "Move",
          slides: [
            {
              id: "s1",
              type: "theory",
              title: "Definition",
              content: "The fundamental force law in electrodynamics. A charge $q$ moving with velocity $\\mathbf{v}$ in electric field $\\mathbf{E}$ and magnetic field $\\mathbf{B}$ experiences a force:\n\n$$ \\mathbf{F} = q(\\mathbf{E} + \\mathbf{v} \\times \\mathbf{B}) $$\n\n**Key Property**: The magnetic force $\\mathbf{F}_{mag} = q(\\mathbf{v} \\times \\mathbf{B})$ is always perpendicular to both $\\mathbf{v}$ and $\\mathbf{B}$."
            },
            {
              id: "q1",
              type: "fill-blank",
              title: "Work and Energy",
              content: "Because the magnetic force is perpendicular to velocity, it does ",
              segments: [
                { id: "1", isBlank: true, correctValue: "zero" },
                { id: "2", text: " work. Magnetic forces may alter the direction of a particle but never its ", isBlank: false },
                { id: "3", isBlank: true, correctValue: "speed" },
                { id: "4", text: ".", isBlank: false }
              ],
              wordBank: ["positive", "negative", "zero", "speed", "charge"]
            },
            {
              id: "s2",
              type: "theory",
              title: "Cyclotron Motion",
              content: "In a uniform magnetic field $\\mathbf{B}$ (with $\\mathbf{E}=0$), a particle moves in a circle. The magnetic force provides the centripetal acceleration:\n\n$$ qvB = \\frac{mv^2}{R} \\implies R = \\frac{mv}{qB} $$\n\n$R$ is the cyclotron radius (or Larmor radius)."
            }
          ]
        },
        {
          id: "lesson-currents",
          title: "Force on Currents",
          description: "Macroscopic manifestation.",
          icon: "Activity",
          slides: [
            {
              id: "s1",
              type: "theory",
              title: "From Charge to Current",
              content: "Since current is essentially moving charge, a magnetic field exerts a force on a current-carrying wire.\n\nFor a line current $I$ flowing along a path:\n$$ \\mathbf{F}_{mag} = \\int (\\mathbf{v} \\times \\mathbf{B}) dq = \\int I (d\\mathbf{l} \\times \\mathbf{B}) $$\n\nIf $\\mathbf{B}$ is uniform and the wire is straight: $\\mathbf{F} = I(\\mathbf{L} \\times \\mathbf{B})$."
            },
            {
              id: "m1",
              type: "match",
              title: "Current Distributions",
              content: "Match the current type to its differential force element.",
              pairs: [
                { id: "p1", left: "Line Current ($I$)", right: "$I (d\\mathbf{l} \\times \\mathbf{B})$" },
                { id: "p2", left: "Surface Current ($\\mathbf{K}$)", right: "$(\\mathbf{K} \\times \\mathbf{B}) da$" },
                { id: "p3", left: "Volume Current ($\\mathbf{J}$)", right: "$(\\mathbf{J} \\times \\mathbf{B}) d\\tau$" }
              ]
            }
          ]
        }
      ]
    },
    {
      id: "unit-3-1-biot",
      title: "The Biot-Savart Law",
      description: "Calculating Magnetic Fields.",
      color: "duo-green",
      lessons: [
        {
          id: "lesson-biot-law",
          title: "The Law",
          description: "Field of a steady current.",
          icon: "Minimize",
          slides: [
            {
              id: "s1",
              type: "theory",
              title: "Statement",
              content: "The magnetic field $\\mathbf{B}$ at position $\\mathbf{r}$ generated by a steady line current $I$ is:\n\n$$ \\mathbf{B}(\\mathbf{r}) = \\frac{\\mu_0}{4\\pi} \\int \\frac{I d\\mathbf{l}' \\times \\hat{\\rcurs}}{\\rcurs^2} $$\n\nWhere:\n*   $\\mu_0 = 4\\pi \\times 10^{-7}$ N/A$^2$ (Permeability of free space)\n*   $\\vec{\\rcurs} = \\mathbf{r} - \\mathbf{r}'$ (Separation vector)"
            },
            {
              id: "p1",
              type: "proof",
              title: "Example: Infinite Straight Wire",
              content: "Calculate B at distance $s$ from an infinite wire.",
              proofSteps: [
                "From geometry, $d\\mathbf{l}' \\times \\hat{\\rcurs}$ has magnitude $dl' \\cos\\theta$.",
                "Express variables in terms of angle $\\theta$: $l' = s \\tan\\theta$, $\\rcurs = s / \\cos\\theta$.",
                "Differential $dl' = (s / \\cos^2\\theta) d\\theta$.",
                "Integrate from $\\theta_1 = -\\pi/2$ to $\\theta_2 = \\pi/2$.",
                "Result: $B = \\frac{\\mu_0 I}{4\\pi s} \\int_{-\\pi/2}^{\\pi/2} \\cos\\theta d\\theta = \\frac{\\mu_0 I}{2\\pi s}$."
              ]
            }
          ]
        },
        {
          id: "lesson-biot-applications",
          title: "Applications",
          description: "Circular Loops and more.",
          icon: "Circle",
          slides: [
            {
              id: "s1",
              type: "theory",
              title: "Circular Loop",
              content: "For a circular loop of radius $R$ carrying current $I$, the field on the axis at distance $z$ is:\n\n$$ \\mathbf{B}(z) = \\frac{\\mu_0 I}{2} \\frac{R^2}{(R^2 + z^2)^{3/2}} \\hat{z} $$\n\nAt the center ($z=0$), this simplifies to $B = \\frac{\\mu_0 I}{2R}$."
            },
            {
              id: "q1",
              type: "quiz",
              title: "Field Direction",
              content: "How do you determine the direction of the B-field from a current loop?",
              options: [
                { id: "1", text: "Left Hand Rule", isCorrect: false, explanation: "Used for motors/forces." },
                { id: "2", text: "Right Hand Rule", isCorrect: true, explanation: "Curl fingers in direction of current, thumb points to B." },
                { id: "3", text: "Lenz's Law", isCorrect: false, explanation: "This relates to induction." }
              ]
            }
          ]
        }
      ]
    }
  ]
};