const DIAGRAM_BASE = '../diagrams/';
const DATA_SOURCES = {
 use: 'live',
 mock: [
  "../../flow-library/app/mock/mock.courses.js",
  "../../flow-library/app/mock/mock.concepts.js",
  "../../flow-library/app/mock/mock.objective.js",
  "../../flow-library/app/mock/mock.written.js",
  "../../flow-library/app/mock/mock.pyq.js"
],
 live: [
  "../data/syllabus.js",
  "../data/ch01.concepts.js",
  "../data/ch01.written.js",
  "../data/ch01.objective.js",
  "../data/ch02.concepts.js",
  "../data/ch02.written.js",
  "../data/ch02.objective.js",
  "../data/ch03.concepts.js",
  "../data/ch03.written.js",
  "../data/ch03.objective.js",
  "../data/ch04.concepts.js",
  "../data/ch04.written.js",
  "../data/ch04.objective.js",
  "../data/ch05.concepts.js",
  "../data/ch05.written.js",
  "../data/ch05.objective.js",
  "../data/ch06.concepts.js",
  "../data/ch06.written.js",
  "../data/ch06.objective.js",
  "../data/ch07.concepts.js",
  "../data/ch07.written.js",
  "../data/ch07.objective.js",
  "../data/ch08.concepts.js",
  "../data/ch08.written.js",
  "../data/ch08.objective.js",
  "../data/ch09.concepts.js",
  "../data/ch09.written.js",
  "../data/ch09.objective.js",
  "../data/ch10.concepts.js",
  "../data/ch10.written.js",
  "../data/ch10.objective.js",
  "../data/inference.concepts.js",
  "../data/inference.written.js",
  "../data/inference.objective.js",
  "../data/pyq.js",
  "../data/pyq.similar.js"
]
};
