import { Unit } from '../types';

export const UNIT_1_1_4: Unit = {
  id: "unit-1-1-4",
  title: "Index Set Exercises",
  description: "Exercises 7-12: Infinite Unions, Products, and Images",
  color: "duo-blue",
  lessons: [
    {
      id: "les-1-1-4-ex7", title: "Exercise 7: Infinite Families of Sets", description: "Evaluating unions and intersections of an infinite family", icon: "Library",
      slides: [
        { id: "s0", type: "example_q", title: "Exercise 7", content: "For each $n \\in \\mathbb{N}$, let $A_n = \\{(n+1)k : k \\in \\mathbb{N}\\}$.\n\n(a) What is $A_1 \\cap A_2$?\n(b) Determine the sets $\\bigcup_{n \\in \\mathbb{N}} A_n$ and $\\bigcap_{n \\in \\mathbb{N}} A_n$." },
        { id: "s1", type: "solution", title: "Interactive Solution", content: "**Goal: Evaluate the infinite family.**", interactiveSteps: [
            { stepText: "First, let's write out the sets. $A_1 = \\{2k\\} = \\{2, 4, 6, 8, \\dots\\}$, the even numbers.\n$A_2 = \\{3k\\} = \\{3, 6, 9, 12, \\dots\\}$, multiples of 3." },
            { prompt: "What is the intersection $A_1 \\cap A_2$?", options: [{ id: "A", text: "Multiples of 6", isCorrect: true, explanation: "Numbers that are both even and multiples of 3 are multiples of 6." }, { id: "B", text: "Multiples of 5", isCorrect: false, explanation: "You multiply the factors (2 and 3), not add them." }], stepText: "(a) $A_1 \\cap A_2 = \\{6k : k \\in \\mathbb{N}\\} = A_5$." },
            { prompt: "Next, the union $\\cup A_n$. Notice $A_1$ has all evens, $A_2$ has multiples of 3, etc. What number from $\\mathbb{N}$ will NEVER be generated by $(n+1)k$ for $n,k \\ge 1$?", options: [{ id: "A", text: "1", isCorrect: true, explanation: "Since $n+1 \\ge 2$ and $k \\ge 1$, the smallest element generated is 2." }, { id: "B", text: "0", isCorrect: false, explanation: "0 is not in $\\mathbb{N}$ in this context." }], stepText: "Every number $\\ge 2$ is in at least one set (since $m = m \\times 1$). So $\\cup A_n = \\mathbb{N} \\setminus \\{1\\}$." },
            { stepText: "Finally, the intersection $\\cap A_n$. Is there any number that is a multiple of *every* integer $n+1$? No. Thus $\\cap A_n = \\emptyset$." }
        ]},
        { id: "s2", type: "numerical", title: "Evaluation", content: "What is the smallest number contained in the set $A_4$?", numericAnswer: 5, numericTolerance: 0 }
      ]
    },
    {
      id: "les-1-1-4-ex8", title: "Exercise 8: Cartesian Graphs", description: "Drawing Cartesian products", icon: "LayoutGrid",
      slides: [
        { id: "s0", type: "example_q", title: "Exercise 8", content: "Draw diagrams in the plane of the Cartesian products $A \\times B$ for the given sets:\n\n(a) $A = \\{x \\in \\mathbb{R} : 1 \\le x \\le 2 \\text{ or } 3 \\le x \\le 4\\}$, $B = \\{x \\in \\mathbb{R} : x = 1 \\text{ or } x = 2\\}$\n(b) $A = \\{1, 2, 3\\}$, $B = \\{x \\in \\mathbb{R} : 1 \\le x \\le 3\\}$" },
        { id: "s1", type: "solution", title: "Interactive Solution", content: "**Goal: Describe the geometry of the products.**", interactiveSteps: [
            { stepText: "(a) Set $A$ consists of two continuous segments on the x-axis: $[1, 2]$ and $[3, 4]$. Set $B$ consists of two discrete points on the y-axis: $1$ and $2$." },
            { prompt: "What geometric shape does $A \\times B$ form in part (a)?", options: [{ id: "A", text: "Four horizontal line segments", isCorrect: true, explanation: "The intervals from A form lines at the specific heights given by B." }, { id: "B", text: "Four solid rectangles", isCorrect: false, explanation: "B is discrete, so it has no vertical 'thickness'." }], stepText: "The product forms four horizontal line segments in the plane." },
            { stepText: "(b) Set $A$ is discrete (3 points), while Set $B$ is a continuous interval $[1, 3]$." },
            { stepText: "Therefore, $A \\times B$ forms three vertical line segments at $x=1, x=2, x=3$, each stretching from $y=1$ to $y=3$." }
        ]}
      ]
    },
    {
      id: "les-1-1-4-ex9", title: "Exercise 9: Is it a Function?", description: "Testing relations", icon: "HelpCircle",
      slides: [
        { id: "s0", type: "example_q", title: "Exercise 9", content: "Let $A := B := \\{x \\in \\mathbb{R} : -1 \\le x \\le 1\\}$ and consider the subset $C := \\{(x,y) : x^2 + y^2 = 1\\}$ of $A \\times B$.\n\nIs this set a function? Explain." },
        { id: "s1", type: "solution", title: "Interactive Solution", content: "**Goal: Determine if C satisfies the definition of a function.**", interactiveSteps: [
            { stepText: "The set $C$ represents all points on a circle of radius 1 centered at the origin." },
            { prompt: "Recall Definition 1.1.6: A function requires every input $x$ to map to a UNIQUE output $y$. Does this circle satisfy that?", options: [{ id: "A", text: "No", isCorrect: true, explanation: "For x=0, y can be 1 or -1. This violates uniqueness." }, { id: "B", text: "Yes", isCorrect: false, explanation: "Check x = 0." }], stepText: "No, it is not a function." },
            { stepText: "For example, both $(0, 1) \\in C$ and $(0, -1) \\in C$. Since one $x$-value maps to multiple $y$-values, it fails the vertical line test." }
        ]},
        { id: "s2", type: "fill_in_blank", title: "Concept Check", content: "The equation $x^2 + y^2 = 1$ is a valid ___, but not a valid function.", blankAnswer: "relation" }
      ]
    },
    {
      id: "les-1-1-4-ex10", title: "Exercise 10: Direct and Inverse Images", description: "Calculating images of sets", icon: "Image",
      slides: [
        { id: "s0", type: "example_q", title: "Exercise 10", content: "Let $f(x) := 1/x^2, x \\neq 0, x \\in \\mathbb{R}$.\n\n(a) Determine the direct image $f(E)$ where $E := \\{x \\in \\mathbb{R} : 1 \\le x \\le 2\\}$.\n(b) Determine the inverse image $f^{-1}(G)$ where $G := \\{x \\in \\mathbb{R} : 1 \\le x \\le 4\\}$." },
        { id: "s1", type: "solution", title: "Interactive Solution", content: "**Goal: Map the intervals.**", interactiveSteps: [
            { stepText: "(a) We plug the interval $1 \\le x \\le 2$ into $f(x) = 1/x^2$. Since $1/x^2$ is decreasing for positive $x$, the maximum value occurs at $x=1$ and the minimum at $x=2$." },
            { prompt: "What is the resulting interval $f(E)$?", options: [{ id: "A", text: "[1/4, 1]", isCorrect: true, explanation: "f(2) = 1/4, f(1) = 1." }, { id: "B", text: "[1, 2]", isCorrect: false, explanation: "Apply the function to the endpoints." }], stepText: "(a) $f(E) = [1/4, 1]$." },
            { stepText: "(b) We want $f^{-1}(G)$, meaning we need to find all $x$ such that $1 \\le 1/x^2 \\le 4$." },
            { stepText: "Taking reciprocals (and flipping inequalities): $1/4 \\le x^2 \\le 1$. Taking square roots gives $1/2 \\le |x| \\le 1$." },
            { stepText: "This results in two intervals: $f^{-1}(G) = [-1, -1/2] \\cup [1/2, 1]$. Goal reached!" }
        ]}
      ]
    },
    {
      id: "les-1-1-4-ex11", title: "Exercise 11: Composition Images", description: "Images through composite functions", icon: "Layers",
      slides: [
        { id: "s0", type: "example_q", title: "Exercise 11", content: "Let $g(x) := x^2$ and $f(x) := x + 2$ for $x \\in \\mathbb{R}$, and let $h$ be the composite function $h := g \\circ f$.\n\n(a) Find the direct image $h(E)$ of $E := \\{x \\in \\mathbb{R} : 0 \\le x \\le 1\\}$.\n(b) Find the inverse image $h^{-1}(G)$ of $G := \\{x \\in \\mathbb{R} : 0 \\le x \\le 4\\}$." },
        { id: "s1", type: "solution", title: "Interactive Solution", content: "**Goal: Evaluate the composite function.**", interactiveSteps: [
            { stepText: "First, find the formula for $h(x)$. $h(x) = g(f(x)) = g(x+2) = (x+2)^2$." },
            { prompt: "(a) For $x \in [0, 1]$, $(x+2)$ ranges from $2$ to $3$. What is $h(E)$?", options: [{ id: "A", text: "[4, 9]", isCorrect: true, explanation: "Squaring the interval [2, 3] gives [4, 9]." }, { id: "B", text: "[0, 1]", isCorrect: false, explanation: "Evaluate the function endpoints." }], stepText: "(a) $h(E) = [4, 9]$." },
            { prompt: "(b) For the inverse image, we set $0 \\le (x+2)^2 \\le 4$. Taking the square root gives...", options: [{ id: "A", text: "$-2 \\le x+2 \\le 2$", isCorrect: true, explanation: "Taking the square root of $y^2 \\le 4$ gives $|y| \\le 2$." }, { id: "B", text: "$0 \\le x+2 \\le 2$", isCorrect: false, explanation: "A square can be generated by negative numbers too." }], stepText: "We have $-2 \\le x+2 \\le 2$." },
            { stepText: "Subtracting 2 from all sides gives $-4 \\le x \\le 0$. Thus, $h^{-1}(G) = [-4, 0]$. Goal reached!" }
        ]}
      ]
    },
    {
      id: "les-1-1-4-ex12", title: "Exercise 12: Intersection Mismatch", description: "Why f(A ∩ B) is not always f(A) ∩ f(B)", icon: "AlertTriangle",
      slides: [
        { id: "s0", type: "example_q", title: "Exercise 12", content: "Let $f(x) := x^2$ for $x \\in \\mathbb{R}$, and let $E := [-1, 0]$ and $F := [0, 1]$.\n\nShow that $f(E \\cap F)$ is a proper subset of $f(E) \\cap f(F)$." },
        { id: "s1", type: "solution", title: "Interactive Solution", content: "**Goal: Calculate both sides and compare.**", interactiveSteps: [
            { stepText: "First, let's find $E \\cap F$. Since $E=[-1, 0]$ and $F=[0, 1]$, their only common point is $0$. So $E \\cap F = \\{0\\}$." },
            { prompt: "What is $f(E \\cap F)$?", options: [{ id: "A", text: "{0}", isCorrect: true, explanation: "f(0) = 0^2 = 0." }, { id: "B", text: "Empty set", isCorrect: false, explanation: "0 is in the set, and f(0)=0." }], stepText: "Thus, $f(E \\cap F) = \\{0\\}$." },
            { stepText: "Now calculate $f(E)$ and $f(F)$ separately. Squaring $[-1, 0]$ gives $[0, 1]$. Squaring $[0, 1]$ gives $[0, 1]$. Thus $f(E) = [0, 1]$ and $f(F) = [0, 1]$." },
            { stepText: "Their intersection is $f(E) \\cap f(F) = [0, 1] \\cap [0, 1] = [0, 1]$." },
            { stepText: "Comparing the two: $\\{0\\}$ is clearly a proper subset of $[0, 1]$. Goal reached!" }
        ]},
        { id: "s2", type: "quiz", title: "Follow-up", content: "What happens if 0 is deleted from the sets E and F?", options: [{ id: "A", text: "$f(E \\cap F) = \\emptyset$, but $f(E) \\cap f(F) = (0, 1]$", isCorrect: true, explanation: "The intersection becomes empty, but the squared images still heavily overlap!" }, { id: "B", text: "They become equal.", isCorrect: false, explanation: "The mismatch actually becomes more severe." }] }
      ]
    }
  ]
};