/* ══════════════════════════════════════════════════════════════════════════
   THE DATA SEAM — Class 8 Mathematics · Math Base
   ══════════════════════════════════════════════════════════════════════════ */

const DIAGRAM_BASE = '../diagrams/';

const DATA_SOURCES = {
  use: 'live',

  mock: [
    'mock/mock.courses.js',
    'mock/mock.concepts.js',
    'mock/mock.objective.js',
    'mock/mock.written.js',
    'mock/mock.pyq.js'
  ],

  live: [
    '../data/syllabus.js',
    '../data/school.js',
    '../data/ch1.squares.js',
    '../data/questions.ch1.js',
    '../data/ch2.triangles.js',
    '../data/questions.ch2.js',
    '../data/ch3.identities.js',
    '../data/questions.ch3.js',
    '../data/ch4.polygons.js',
    '../data/questions.ch4.js',
    '../data/ch5.money-maths.js',
    '../data/questions.ch5.js',
    '../data/ch6.quadrilaterals.js',
    '../data/questions.ch6.js',
    '../data/ch7.ratio.js',
    '../data/questions.ch7.js',
    '../data/ch8.quad-area.js',
    '../data/questions.ch8.js',
    '../data/ch9.negative-numbers.js',
    '../data/questions.ch9.js',
    '../data/ch10.statistics.js',
    '../data/questions.ch10.js',
    '../data/ch11.equations.js',
    '../data/questions.ch11.js',
    '../data/ch12.parallel-lines.js',
    '../data/questions.ch12.js',
    '../data/ch13.prisms.js',
    '../data/questions.ch13.js',
    '../data/ch9.1.area.js',
    '../data/questions.ch9.1.js',
    '../data/ch9.2.decimal-forms.js',
    '../data/questions.ch9.2.js',
    '../data/ch9.3.pairs-of-equations.js',
    '../data/questions.ch9.3.js',
    '../data/ch9.4.new-numbers.js',
    '../data/questions.ch9.4.js',
    '../data/ch9.5.circles.js',
    '../data/questions.ch9.5.js',
    '../data/ch9.6.parallel-lines.js',
    '../data/questions.ch9.6.js',
    '../data/ch9.7.similar-triangles.js',
    '../data/questions.ch9.7.js',
    '../data/ch9.8.polynomials.js',
    '../data/questions.ch9.8.js',
    '../data/ch9.9.circle-measures.js',
    '../data/questions.ch9.9.js',
    '../data/ch9.10.real-numbers.js',
    '../data/questions.ch9.10.js',
    '../data/ch9.11.prisms.js',
    '../data/questions.ch9.11.js',
    '../data/ch9.12.proportion.js',
    '../data/questions.ch9.12.js',
    '../data/ch9.13.statistics.js',
    '../data/questions.ch9.13.js',
    '../data/ch10.1.arithmetic-sequences.js',
    '../data/questions.ch10.1.js',
    '../data/ch10.2.circles.js',
    '../data/questions.ch10.2.js',
    '../data/ch10.3.mathematics-of-chance.js',
    '../data/questions.ch10.3.js',
    '../data/ch10.4.second-degree-equations.js',
    '../data/questions.ch10.4.js',
    '../data/ch10.5.trigonometry.js',
    '../data/questions.ch10.5.js',
    '../data/ch10.6.coordinates.js',
    '../data/questions.ch10.6.js',
    '../data/ch10.7.tangents.js',
    '../data/questions.ch10.7.js',
    '../data/ch10.8.solids.js',
    '../data/questions.ch10.8.js',
    '../data/ch10.9.geometry-and-algebra.js',
    '../data/questions.ch10.9.js',
    '../data/ch10.10.polynomials.js',
    '../data/questions.ch10.10.js',
    '../data/ch10.11.statistics.js',
    '../data/questions.ch10.11.js',
    '../data/pyq.js'
  ]
};
