#!/usr/bin/env python3
"""Authoring DSL for Optics content.

Content lives in authoring/*.py as plain Python with RAW strings, so TeX is written
with single backslashes (r'\\frac{1}{f}' is written r'\frac{1}{f}'). This script imports
each authoring file, collects what it registered, and writes data/*.js with every
string JSON-escaped, so a lost backslash cannot happen.

    python3 tools/author.py            # regenerate every data file
    python3 tools/author.py authoring/m1.written.py   # just one authoring file
    node tools/check_tex.js            # then gate it

Helpers (each returns nothing; they register into the module's lists):
    C(id, sec, kind, title, one, statement, intuition, needs=[], traps=[], cards=[],
      proof=None, tier='core', img=None)
    proof = dict(idea=, why=, rungs=[(why, m, meaning), ...], ends=)
    cards = [(q, a)] -> first becomes kind 'state', the rest 'recall'
    W(id, sec, marks, title, source, prompt, tests, approach, solution, trap)
    O(id, sec, type, prompt, options, answer, solution, tested, trap, tests, twist=None,
      marks=1, neg=None, time=60)
    P(id, year, exam_label, qno, marks, sec, tests, title, prompt, approach, solution, trap)
"""
import glob
import importlib.util
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
BANNER = '/* GENERATED by tools/author.py from authoring/%s — edit the .py, never this file. */\n\n'

REG = {'concepts': [], 'written': [], 'objective': [], 'pyq': []}
STEPS = {}          # concept id -> {'kind', 'stages', 'meanings', 'sim'}  (authoring/steps.py)
NOFIG = {}          # (concept id, step index) -> why that step needs no picture
NOSIM = {}          # concept id -> why that proof has no simulation


def C(id, sec, kind, title, one, statement, intuition, needs=(), traps=(), cards=(),
      proof=None, tier='core', img=None, figs=None):
    d = {'id': id, 'sec': sec, 'kind': kind, 'tier': tier, 'title': title, 'oneLine': one,
         'statement': statement.strip(), 'intuition': intuition.strip(),
         'needs': list(needs), 'figs': list(figs or []),
         'traps': [t.strip() for t in traps]}
    if img:
        d['img'] = list(img)
    if proof:
        d['proof'] = {
            'idea': proof['idea'], 'why': proof.get('why', ''),
            'rungs': [{'why': r[0], 'm': r[1], 'meaning': r[2] if len(r) > 2 else ''}
                      for r in proof['rungs']],
            'ends': proof.get('ends', '')}
    d['cards'] = [{'q': q.strip(), 'a': a.strip(), 'kind': 'state' if i == 0 else 'recall'}
                  for i, (q, a) in enumerate(cards)]
    REG['concepts'].append(d)


def W(id, sec, marks, title, source, prompt, tests, approach, solution, trap=''):
    REG['written'].append({
        'id': id, 'course': 'op', 'sec': sec, 'marks': marks, 'title': title,
        'source': source, 'prompt': prompt.strip(), 'tests': list(tests),
        'approach': approach.strip(), 'solution': solution.strip(), 'trap': trap.strip()})


def O(id, sec, type, prompt, options, answer, solution, tested, trap, tests, twist=None,
      marks=1, neg=None, time=60):
    if neg is None:
        neg = {'MCQ': -0.33, 'MSQ': 0, 'NAT': 0}[type]
    d = {'id': id, 'course': 'op', 'sec': sec, 'type': type, 'marks': marks, 'neg': neg,
         'negLabel': {0: '0', -0.33: '−1/3', -0.66: '−2/3'}.get(neg, str(neg)), 'time': time,
         'prompt': prompt.strip(), 'answer': answer, 'solution': solution.strip(),
         'tested': tested, 'trap': trap, 'tests': list(tests)}
    if options:
        d['options'] = [{'k': 'ABCD'[i], 't': t} for i, t in enumerate(options)]
    if twist:
        d['twist'] = {'q': twist[0], 'a': twist[1]}
    REG['objective'].append(d)


def P(id, year, exam, qno, marks, sec, tests, title, prompt, approach, solution, trap=''):
    REG['pyq'].append({
        'id': id, 'course': 'op', 'exam': exam, 'year': year, 'paper': 'PHY5B08', 'qno': qno,
        'marks': marks, 'sec': sec, 'tests': list(tests), 'title': title,
        'prompt': prompt.strip(), 'approach': approach.strip(), 'solution': solution.strip(),
        'trap': trap.strip()})


NAMES = {'concepts': ('CONCEPTS', 'op-'), 'written': ('QUESTIONS', 'questions.'),
         'objective': ('OBJECTIVE', 'objective.'), 'pyq': ('PYQ', 'pyq.')}


def S(cid, kind, stages, meanings, sim=None):
    STEPS[cid] = {'kind': kind, 'stages': list(stages), 'meanings': list(meanings), 'sim': sim}


def NF(cid, idx, why):
    NOFIG[(cid, idx)] = why


def NS(cid, why):
    NOSIM[cid] = why


def apply_steps(items):
    """Merge the teaching layer onto concepts: each proof step's plain-language meaning and its
    diagram, and the simulation a concept hosts. A length mismatch is an error, never a guess."""
    for c in items:
        st = STEPS.get(c['id'])
        if not st:
            continue
        rungs = (c.get('proof') or {}).get('rungs', [])
        if len(st['meanings']) != len(rungs) or len(st['stages']) != len(rungs):
            raise SystemExit('steps.py: %s has %d proof steps but %d meanings / %d stages'
                             % (c['id'], len(rungs), len(st['meanings']), len(st['stages'])))
        for r, m, g in zip(rungs, st['meanings'], st['stages']):
            r['meaning'] = m
            if g:
                r['fig'] = {'k': st['kind'], 's': g}
        if st['sim']:
            c['sim'] = st['sim']
    return items


def load(path):
    spec = importlib.util.spec_from_file_location('auth_' + os.path.basename(path)[:-3], path)
    mod = importlib.util.module_from_spec(spec)
    mod.C, mod.W, mod.O, mod.P, mod.S, mod.NF, mod.NS = C, W, O, P, S, NF, NS
    spec.loader.exec_module(mod)


def clean(x):
    """A backslash before an apostrophe is only ever an escape that leaked into a RAW string
    (r'...Young\'s...' keeps the backslash). TeX's accent \' is not used in this course."""
    if isinstance(x, str):
        return x.replace("\\'", "'")
    if isinstance(x, list):
        return [clean(v) for v in x]
    if isinstance(x, dict):
        return {k: clean(v) for k, v in x.items()}
    return x


def emit(stem, kind, items):
    name = NAMES[kind][0]
    if kind == 'concepts':
        apply_steps(items)
    items = clean(items)
    out = os.path.join(ROOT, 'data', '%s.js' % stem)
    body = ',\n'.join(json.dumps(x, ensure_ascii=False, indent=1) for x in items)
    with open(out, 'w', encoding='utf-8') as f:
        f.write(BANNER % (stem + '.py'))
        f.write("if (typeof %s === 'undefined') { var %s = []; }\n\n%s.push(\n%s\n);\n"
                % (name, name, name, body))
    return out


def main():
    made = []
    only = [os.path.realpath(a) for a in sys.argv[1:]]
    load(os.path.join(ROOT, 'authoring', 'steps.py'))          # the teaching layer applies to every run
    for path in sorted(glob.glob(os.path.join(ROOT, 'authoring', '*.py'))):
        if only and os.path.realpath(path) not in only:
            continue
        if os.path.basename(path) == 'steps.py':
            continue
        for k in REG:
            REG[k] = []
        load(path)
        stem = os.path.basename(path)[:-3]
        kinds = [k for k, v in REG.items() if v]
        for kind in kinds:
            name = stem if len(kinds) == 1 else stem + '.' + kind
            made.append((emit(name, kind, REG[kind]), len(REG[kind])))
    for p, n in made:
        print('%4d  %s' % (n, os.path.relpath(p, ROOT)))
    if not only:
        write_index()


def write_index():
    """authoring/_concept_index.txt: every concept id, section, kind and title — the list
    an exercise author picks `tests=[...]` ids from."""
    rows = []
    for f in sorted(glob.glob(os.path.join(ROOT, 'data', 'm*.concepts.js'))):
        text = open(f, encoding='utf-8').read()
        body = text[text.index('CONCEPTS.push(') + len('CONCEPTS.push('):text.rindex(');')]
        for c in json.loads('[' + body + ']'):
            rows.append('%s\tsec %s\t%s\t%s' % (c['id'], c['sec'], c['kind'], c['title']))
    open(os.path.join(ROOT, 'authoring', '_concept_index.txt'), 'w', encoding='utf-8').write('\n'.join(rows) + '\n')


if __name__ == '__main__':
    main()
