"""Schematic diagrams for the Optics app, drawn by Codex's image tool.

Each entry: (concept id, slug, what to draw). tools/gen_codex_diagrams.py turns each into
diagrams/light/<id>_<slug>.png and its dark twin. Exact plots (intensity curves, the Cornu
spiral, polarisation ellipses) are NOT here: tools/gen_plots.py draws them from formulas.
"""

STYLE = (
    "A clean textbook physics figure for a university optics course. Pure white background, "
    "thin dark-slate linework, generous white space, landscape 3:2. Use ONE accent colour, "
    "magenta (#a3186f), for the ray or quantity that matters most, and teal (#0d9488) for secondary rays; "
    "everything else dark slate or light grey. Labels in a clean sans-serif with italic math symbols "
    "(subscripts as real subscripts). Label ONLY what is listed below, spelled exactly, with no extra text, "
    "no title, no caption, no border, no watermark, no drop shadows, no gradients. "
    "Physical accuracy matters more than decoration: angles, equal lengths and ray directions must be correct. "
    "The drawing is: "
)

SPECS = [
 ('c.1.1.1', 'optical_path',
  "Two points A (left) and B (right) in a uniform medium. The straight segment from A to B in magenta with an arrowhead, labelled 'actual ray: stationary optical path'. Two faint dashed curved detours from A to B, one above and one below, labelled 'nearby paths'. Beside A write 'A', beside B write 'B'. Below, one line: L = ∫ n ds."),
 ('c.1.1.2', 'reflection_image',
  "A horizontal plane mirror drawn as a thick line with short hatch marks below it. Point A above-left and point B above-right, at different heights. The reflection point P on the mirror between them. Solid magenta path A to P to B with arrowheads. The mirror image A' below the mirror directly under A at equal depth, joined by a straight dashed teal line A' to P to B (it must be one straight line). A dashed vertical normal at P. Mark the angle of incidence i and angle of reflection r with small arcs, visibly equal. Labels: A, B, P, A', i, r."),
 ('c.1.1.3', 'snell_crossing',
  "A horizontal interface line. Above it medium 1 labelled n₁, below it medium 2 labelled n₂ (subscripts). Point A upper-left at height a above the interface, point B lower-right at depth b below it. The ray from A to a crossing point R on the interface to B, in magenta, bending toward the normal in the lower medium. A dashed vertical normal through R. Mark θ₁ (upper angle from the normal) and θ₂ (lower angle from the normal), θ₂ visibly smaller. Mark along the interface the distance x (from below A to R) and d − x (from R to below B), with dimension arrows, and the heights a and b with vertical dimension arrows. Labels: A, B, R, n₁, n₂, θ₁, θ₂, a, b, x, d − x."),
 ('c.1.1.4', 'parabola_focus',
  "A parabolic mirror opening to the right: vertex C at the left, focus S on the axis inside it. A vertical dashed directrix line AB further left of the vertex. Three horizontal parallel rays coming in from the right, travelling left, hitting the parabola at points and reflecting through the focus S (magenta). For one ray show the equal lengths: QS from the reflection point Q to the focus, and QL' from Q perpendicular to the directrix, marked equal with matching tick marks. Labels: C, S, Q, L', directrix."),
 ('c.1.2.2', 'spherical_refraction',
  "A spherical refracting surface, convex toward the left, drawn as an arc of a circle whose centre of curvature C lies on the axis to the right. Left of the surface medium n₁, right of it n₂ (n₂ > n₁, subscripts). The horizontal optical axis. Vertex O at the surface on the axis. An object point on the axis to the left at distance u, image point I on the axis to the right at distance v. One ray from the object hits the surface at point P at height h and refracts to I. Draw the radius CP dashed. Mark the small angles α (incident ray with the axis), β (refracted ray with the axis), γ (at C between axis and CP), and θ₁, θ₂ (incident and refracted ray angles to the radius CP). Label R for the radius, u, v, h. Labels: O, C, P, I, n₁, n₂, u, v, R, h, α, β, γ, θ₁, θ₂."),
 ('c.1.2.3', 'surface_foci',
  "Two stacked panels sharing the same convex refracting surface between n₁ (left) and n₂ (right) with n₂ > n₁ and centre of curvature C on the right. Top panel: parallel rays from the left converging after the surface to the second focus F₂ on the axis, with focal distance f₂ marked from the vertex. Bottom panel: rays diverging from the first focus F₁ on the left emerge parallel to the right, with focal distance f₁ marked (F₁ is on the left, closer to the vertex than F₂ is on the right). Labels: n₁, n₂, C, F₁, F₂, f₁, f₂."),
 ('c.1.2.4', 'spherical_mirror',
  "A concave spherical mirror facing right (the reflecting surface curved like a shallow bowl opening toward the object). The optical axis with the centre of curvature C and the focus F at half the distance from the vertex O to C. An object arrow standing on the axis beyond C, and its real, inverted, smaller image between F and C, formed by two rays (one parallel to the axis reflected through F, one through C reflected back on itself). Mark the distances u and v from the vertex. Labels: O, F, C, u, v, object, image."),
 ('c.1.3.1', 'thin_lens_surfaces',
  "A thin biconvex glass lens in air, with refractive index n marked inside. Its first surface has centre of curvature C₁ on the right (radius R₁) and its second surface has centre of curvature C₂ on the left (radius R₂), both centres on the axis and both radii drawn as dashed lines from the surfaces to the centres. An object point on the axis at distance u on the left; the ray from it passes through the lens and reaches the image point on the axis at distance v on the right. Labels: n, R₁, R₂, C₁, C₂, u, v, and 'air' on both sides."),
 ('c.1.3.3', 'two_lenses',
  "Two thin convex lenses L₁ and L₂ on a common axis separated by distance d. A ray parallel to the axis at height h₁ enters L₁, bends toward the focus F₁' of L₁, meets L₂ at a lower height h₂, bends again and crosses the axis at point F. Extend the incoming ray and the final ray backward/forward with dashed lines meeting at the equivalent principal plane. Mark f₁ (focal length of L₁), f₂ (of L₂), d, h₁, h₂, and the effective focal length F. Labels: L₁, L₂, F₁', F, f₁, f₂, d, h₁, h₂, F."),
 ('c.1.3.4', 'three_rays',
  "Two panels. Left panel: a thin convex lens with focal points F₁ (left) and F₂ (right) and 2F marked on both sides. An object arrow beyond 2F on the left. Three principal rays: one parallel to the axis then through F₂, one through the lens centre undeviated, one through F₁ then parallel to the axis. They meet forming a real inverted image between F₂ and 2F on the right. Right panel: a thin concave lens with an upright object arrow; the ray parallel to the axis diverges as if from the near focus, the central ray goes straight, and dashed backward extensions form a smaller upright virtual image on the same side as the object. Labels: F₁, F₂, 2F, object, image, virtual image."),
 ('c.1.4.1', 'newton_distances',
  "A thin convex lens on the optical axis with the two principal foci F₁ (left) and F₂ (right), each at distance f from the lens, marked. An object arrow to the left of F₁ at distance x measured from F₁, and its inverted image to the right of F₂ at distance x' measured from F₂. Draw dimension arrows for f (lens to F₁), f (lens to F₂), x (from F₁ to the object) and x' (from F₂ to the image), and two rays (parallel ray through F₂, and ray through F₁ emerging parallel) forming the image. Labels: F₁, F₂, f, f, x, x', object, image."),
 ('c.2.1.1', 'phasor_addition',
  "A phasor diagram. Draw a first arrow a₁ from the origin along the horizontal axis, then a second arrow a₂ attached to its tip making an interior angle so that the exterior turning angle is δ = φ₁ − φ₂ (show the angle δ between the direction of a₁ extended and a₂), and the resultant arrow a from the origin to the end of a₂ in magenta. Draw the dashed triangle closure and write the law a² = a₁² + a₂² + 2a₁a₂ cos δ beneath. Include a small circle at the origin and light axes. Labels: a₁, a₂, a, δ."),
 ('c.2.2.2', 'wave_train',
  "A horizontal time/space line showing a sinusoidal wave that consists of short finite wave trains: about five separate sinusoidal bursts of equal length placed one after another, each burst with a different phase offset at its start (visible phase jumps between bursts). Mark the length of one burst with a dimension arrow labelled L_c = cτ_c (coherence length) and the duration τ_c. Label the phase jumps with small arrows 'phase jump'. Labels: L_c, τ_c, phase jump."),
 ('c.2.3.1', 'young_geometry',
  "Young's double-slit experiment in side view. On the left a vertical barrier with two slits S₁ (upper) and S₂ (lower) separated by d, with a horizontal central axis through the midpoint. A vertical screen on the right at distance D. A point P on the screen at height x above the axis O. Rays S₁P and S₂P in magenta, and the small right-angle construction near S₁ showing the path difference Δ = S₂P − S₁P as a short segment. On the far right a narrow strip beside the screen showing alternating bright and dark fringes with fringe width β marked between two bright fringes. Labels: S₁, S₂, d, D, P, O, x, Δ, β."),
 ('c.2.3.3', 'hyperbolic_fringes',
  "Two coherent point sources S₁ and S₂ on a vertical line. Draw a family of hyperbolas (loci of constant path difference S₂P − S₁P = 0, ±λ, ±2λ) opening left and right, with the m = 0 locus the straight perpendicular bisector line. Label the loci 0, ±λ, ±2λ. Far to the right a vertical screen line where the hyperbolas cut the screen at nearly straight, equally spaced points marked as bright fringes. Labels: S₁, S₂, 0, λ, 2λ, −λ, −2λ, screen."),
 ('c.2.3.4', 'plate_shift',
  "Young's double slit: barrier with slits S₁ (upper) and S₂ (lower). A thin transparent plate of thickness t and refractive index n covering the upper slit S₁, drawn as a small shaded rectangle in front of it. A screen on the right at distance D. Beside the screen draw two fringe patterns side by side: an original pattern (dashed, light grey) with central maximum O on the axis, and the shifted pattern (magenta) whose central maximum has moved up, toward the covered slit, by Δx, marked with a dimension arrow. Labels: S₁, S₂, n, t, D, O, Δx, 'original', 'shifted'."),
 ('c.2.4.1', 'fresnel_mirrors',
  "Fresnel's two-mirror arrangement, drawn simply and to scale-ish. Two short plane mirrors M₁ and M₂ meet at the point O forming a very shallow V (angle α between their surfaces, exaggerated to about 10°), reflecting sides facing UP-RIGHT toward a vertical screen on the right. A point source S (a slit) sits above and to the left of O, at distance a from O (dashed line S–O labelled a). Each mirror reflects a beam from S to the right, and each reflected beam looks as if it came from a virtual image of S: draw the two virtual images S₁ and S₂ BELOW the mirrors, both on a dashed circular arc centred at O with radius a (so O–S₁ and O–S₂ are both labelled a). Draw the reflected rays as solid teal lines that continue to the screen and, as dashed lines, backwards from the mirrors to S₁ and S₂. The region where the two reflected beams overlap in front of the screen is lightly shaded. Show the separation d between S₁ and S₂ with a dimension line and the distance b from O to the screen. Labels: S, S₁, S₂, M₁, M₂, O, α, a, a, b, d."),
 ('c.2.4.2', 'biprism',
  "Fresnel's biprism seen from above: a biprism (two thin prisms joined base to base, drawn as a flat wide triangle-pair with a small refracting angle α at each outer apex). A slit source S on the left at distance a. Two refracted beams from the two halves appear to come from two virtual sources S₁ and S₂ separated by d (dashed backward extensions). The beams overlap on a screen at distance b to the right of the biprism, the overlapping region shaded lightly. Labels: S, S₁, S₂, α, a, b, d, biprism, screen."),
 ('c.2.5.2', 'lloyds_mirror',
  "Lloyd's mirror: a horizontal plane mirror as a thick line with hatching below, of finite length. A source slit S at small height h above the mirror on the left. Its virtual image S' at depth h below the mirror. A direct ray from S to a point P on a vertical screen on the right, and a reflected ray from the mirror to P (dashed line from S' through the mirror). The region of overlap shaded lightly. On the screen at the level of the mirror plane mark the dark central fringe. Mark the effective source separation d = 2h and the distance D to the screen. Labels: S, S', h, d = 2h, D, P, 'dark fringe at mirror edge'."),
 ('c.2.6.1', 'thin_film_rays',
  "A thin plane-parallel film of thickness d and refractive index n between air above and air below. An incident ray at angle i hits the top surface at B; part reflects (ray 1, magenta) and part refracts at angle r, travels down to the bottom surface at C, reflects, and returns up to the top surface at D where it emerges (ray 2, teal) parallel to ray 1. Draw the normal at B dashed. Draw the perpendicular from D to ray 1 meeting it at N. Mark BC, CD, BD on the drawing, the thickness d with a dimension arrow, and the angles i and r. Labels: n, d, i, r, B, C, D, N, air."),
 ('c.2.6.2', 'ar_coating',
  "An anti-reflection coating at normal incidence, drawn with three horizontal layers: air on top, a thin coating labelled n_f with thickness d = λ/4n_f, and glass n_g below, with 1 < n_f < n_g. A ray arriving vertically from above (drawn slightly tilted for visibility) produces two reflected rays: one from the top of the coating and one from the coating–glass interface, both leaving upward. Next to the two reflected rays draw their sinusoidal waveforms exactly out of phase (crest against trough) with the word 'cancel'. A transmitted ray continues downward into the glass. Labels: air, n_f, n_g, d = λ/4n_f, 'cancel'."),
 ('c.2.7.1', 'wedge',
  "An air wedge: two flat glass plates in side view touching at the left edge and separated at the right by a thin wire of thickness d, wedge angle θ (exaggerated). Light shines down from above. Above the wedge, in a plan view, straight equally spaced dark fringes parallel to the edge, with fringe width β marked between two neighbouring dark fringes. Mark the distance L from the contact edge to the wire. Labels: θ, d, L, β, wire, 'contact edge'."),
 ('c.2.7.3', 'newton_rings',
  "Two views. Left: a plano-convex lens with its curved face down resting on a flat glass plate, radius of curvature R drawn to the centre of curvature above (dashed), the air-gap thickness d at horizontal distance r from the contact poind marked, r and d with dimension arrows, and light from above with a partially reflecting glass plate at 45° for viewing (optional simple). Right: the resulting Newton's rings seen from above: concentric alternating dark and bright rings, dark central spot, rings getting closer together outward, with the diameter D of one dark ring marked. Labels: R, r, d, D, 'dark centre'."),
 ('c.2.7.4', 'michelson',
  "A Michelson interferometer layout in plan view. A light source S on the left sending a beam to the right onto a beam splitter at 45° in the centre. One arm goes up to a fixed mirror M₁; the other continues right through a compensating plate to a movable mirror M₂ mounted on a micrometer screw. The recombined beams go down to the observer/detector D. Show the beams as thin magenta lines with arrowheads. Mark the arm lengths d₁ and d₂. Labels: S, beam splitter, compensating plate, M₁, M₂, micrometer, d₁, d₂, detector."),
 ('c.3.1.2', 'single_slit_setup',
  "Single-slit Fraunhofer diffraction setup: a plane wave (vertical wavefronts) incident from the left on a slit of width b in a barrier; a converging lens after the slit; a screen at the lens focal plane on the right with an intensity profile drawn on the right of the screen: a tall central maximum with weak side maxima. Draw the two edge rays leaving the slit at angle θ and the small right-angle construction showing the path difference b sin θ. Mark the first minima at both sides of the central maximum. Labels: b, θ, b sin θ, lens, screen, 'central maximum', 'first minimum'."),
 ('c.3.3.2', 'grating_orders',
  "A diffraction grating in side view: a vertical barrier with many equally spaced slits of spacing d. A plane wave incident from the left. On the right, the diffracted beams as rays fanning out at angles: the zeroth order straight ahead, and first and second orders above and below at angles θ₁ and θ₂. Near two adjacent slits draw the small right-angle triangle showing the path difference d sin θ = mλ. Labels: d, θ₁, θ₂, 'm = 0', 'm = +1', 'm = −1', 'm = +2', 'm = −2', d sin θ = mλ."),
 ('c.3.4.1', 'half_period_zones',
  "Fresnel half-period zones. Left panel (side view): a plane wavefront as a vertical line, an observation point P at distance d on the axis to the right; circles of increasing radius on the wavefront marked r₁, r₂, r₃ and the corresponding straight paths to P labelled d + λ/2, d + λ, d + 3λ/2. Right panel (front view): concentric circles of radii r₁, r₂, r₃, r₄ on the wavefront forming annular zones, alternate zones lightly shaded, the first zone labelled 1, the next 2, 3, 4. Labels: P, d, r₁, r₂, r₃, d + λ/2, d + λ, d + 3λ/2, 1, 2, 3, 4."),
 ('c.3.4.3', 'zone_plate',
  "A Fresnel zone plate. Left: front view of a disc of concentric rings, alternate zones opaque (dark) and clear (white), radii growing as √n so rings get thinner outward, first zone radius r₁ marked. Right: side view showing a plane wave incident from the left on the zone plate, converging beams to the primary focus at distance f₁ = r₁²/λ and a weaker focus at f₁/3 closer to the plate. Labels: r₁, f₁, f₁/3, 'zone plate', 'primary focus'."),
 ('c.4.1.1', 'polarisation_states',
  "A grid of six small square panels, each showing the electric-field vector tip path viewed head-on with the beam coming toward the viewer, on light axes: (1) linear polarised: a straight double-headed line at 45°; (2) right circular: a circle with an arrow going clockwise; (3) left circular: a circle with an arrow going anticlockwise; (4) elliptical: a tilted ellipse with an arrow; (5) unpolarised: many short random lines through the centre in all directions; (6) partially polarised: many random lines with a few longer ones along one direction. Caption under each panel exactly: 'linear', 'right circular', 'left circular', 'elliptical', 'unpolarised', 'partially polarised'."),
 ('c.4.2.1', 'brewster',
  "Reflection at the Brewster angle. A horizontal air/glass interface, air above (n = 1) and glass below (n). An incident ray coming from the upper left at angle θ_B to the vertical normal at point of incidence, a reflected ray up to the right also at θ_B, and a refracted ray into the glass at angle θ_r, with the reflected and refracted rays exactly perpendicular; mark the right angle between them with a small square. On the reflected ray draw small dots (E perpendicular to the plane of the page) meaning 'polarised perpendicular to the plane of incidence'. On the incident ray draw both dots and short double arrows meaning unpolarised. Draw a small double arrow (dipole) in the glass along the direction of the reflected ray, labelled 'dipole cannot radiate along its axis'. Labels: θ_B, θ_r, air, glass, n, 'tan θ_B = n'."),
 ('c.4.2.3', 'nicol_prism',
  "A Nicol prism cross-section: a long calcite parallelogram cut into two halves along a diagonal plane, joined with a thin layer of Canada balsam (drawn as a thin line, labelled). An unpolarised ray enters at the left face and splits into two rays: the ordinary o-ray, which hits the balsam layer beyond the critical angle and is totally reflected to the side face where a black absorbing (blackened) surface is marked; and the extraordinary e-ray, which passes through the balsam and leaves at the right face parallel to the incident direction, labelled plane-polarised. Mark the o-ray with dots and the e-ray with a double arrow. Labels: 'Canada balsam', 'o-ray', 'e-ray', 'blackened face', 'unpolarised', 'plane polarised', 'total reflection'."),
 ('c.4.3.1', 'polariser_analyser',
  "Left to right along a horizontal beam: unpolarised light (a bundle of short double arrows in all directions on a circle, drawn head-on above the beam) → polariser (a disc with a vertical transmission axis drawn with a double arrow) → plane-polarised light with intensity I₀ (a single vertical double arrow) → analyser (a disc with its transmission axis tilted by angle θ from the vertical) → transmitted light with a shorter double arrow along the analyser axis. In an inset show the vector E₀ and its projection E₀ cos θ onto the analyser axis, angle θ marked. Labels: 'unpolarised', 'polariser', 'analyser', I₀, θ, E₀, E₀ cos θ, I = I₀ cos²θ."),
 ('c.4.4.1', 'double_refraction',
  "Double refraction in a calcite rhombohedron. A single unpolarised ray enters the top face of a slab-shaped calcite crystal at normal incidence and splits inside into two rays that diverge slightly: the ordinary ray (o) continues straight down, the extraordinary ray (e) bends sideways; both emerge parallel to each other, separated. Draw the optic axis as a dashed line inside the crystal at an angle to the faces, and shade the principal section plane. Mark the o-ray with dots (vibration perpendicular to the page) and the e-ray with short double arrows in the plane. Labels: 'optic axis', 'o-ray', 'e-ray', 'principal section', 'unpolarised'."),
 ('c.4.4.2', 'huygens_uniaxial',
  "Two panels: Huygens wavefront surfaces of a point source inside a uniaxial crystal, each showing the optic axis as a dashed vertical line through the point. Left panel 'negative crystal (calcite)': a circle (o-wave) and an ellipse (e-wave) that encloses it, touching the circle at the two points on the optic axis, the ellipse wider horizontally. Right panel 'positive crystal (quartz)': a circle (o-wave) enclosing an ellipse (e-wave) that touches the circle at the points on the optic axis, the ellipse narrower horizontally. Circle drawn in teal, ellipse in magenta. Labels: 'optic axis', 'o-wave (sphere)', 'e-wave (ellipsoid)', 'v_e > v_o', 'v_e < v_o'."),
 ('c.4.5.1', 'wave_plate',
  "A quarter-wave plate. Plane-polarised light on the left with its vibration at 45° to the plate axes (a double arrow at 45°), entering a rectangular wave plate whose fast axis and slow axis are drawn as perpendicular arrows on the plate, thickness d. On the right circularly polarised light emerges, drawn as a helical spiral ribbon of constant amplitude. Below the plate draw two small waveforms for the o and e components: same amplitude, the e component ahead of the o component by a quarter wavelength (a quarter period shift indicated with a small bracket labelled 'λ/4'). Labels: 'linear at 45°', 'fast axis', 'slow axis', d, 'λ/4', 'circular'."),
]
