import data from "./src/data/index.js";
const groups = [
  {
    id: "notation",
    name: "Symbols & notation",
    short: "Symbols",
    color: "#ff86ce",
    icon: "✦",
  },
  {
    id: "spaces",
    name: "Vectors & spaces",
    short: "Spaces",
    color: "#74dfc4",
    icon: "◇",
  },
  {
    id: "states",
    name: "States & notation",
    short: "States",
    color: "#a9a0f5",
    icon: "ψ",
  },
  {
    id: "operators",
    name: "Linear operators",
    short: "Operators",
    color: "#e9b573",
    icon: "Â",
  },
  {
    id: "eigen",
    name: "Eigenvalues & spectra",
    short: "Spectra",
    color: "#a6bdf1",
    icon: "λ",
  },
  {
    id: "matrices",
    name: "Matrices & bases",
    short: "Matrices",
    color: "#daa1cb",
    icon: "⊞",
  },
  {
    id: "waves",
    name: "Waves & transforms",
    short: "Waves",
    color: "#71c8e6",
    icon: "∿",
  },
  {
    id: "uncertainty",
    name: "Measurement & uncertainty",
    short: "Uncertainty",
    color: "#e89f93",
    icon: "Δ",
  },
  {
    id: "ground",
    name: "School-level foundations",
    short: "Ground",
    color: "#83949e",
    icon: "·",
  },
];
const symbolNotes = {
  "†": "Dagger Symbol",
  "∗": "Star Symbol",
  "*": "Star Symbol",
  ℏ: "Hbar Symbol",
  ψ: "Psi Symbol",
  φ: "Phi Symbol",
  ϕ: "Phi Symbol",
  Φ: "Phi Symbol",
  λ: "Lambda Symbol",
  Δ: "Delta Symbol",
  δ: "Dirac Delta Symbol",
  "∑": "Summation Symbol",
  "∫": "Integral Symbol",
  "∂": "Partial Derivative Symbol",
  "∞": "Infinity Symbol",
  π: "Pi Symbol",
  α: "Alpha Symbol",
  β: "Beta Symbol",
  θ: "Theta Symbol",
  "≥": "Equality and Inequality Signs",
  "≤": "Equality and Inequality Signs",
  "≠": "Equality and Inequality Signs",
};
const topicGlyphs = {
  spaces: "V",
  states: "\\psi",
  operators: "\\hat A",
  eigen: "\\lambda",
  matrices: "A",
  waves: "\\psi(x)",
  uncertainty: "\\Delta",
  ground: "x",
  notation: "\\ast",
};

export default {
  ...data,
  groups,
  symbolNotes,
  topicGlyphs,
  glyphs: {
    "Bra-ket Brackets": "\\langle\\,\\rangle",
    "Equality and Inequality Signs": "\\ne",
    "Expectation Brackets": "\\langle A\\rangle",
    "Anticommutator Braces": "\\{A,B\\}",
  },
  meta: {
    id: "quantum-mechanics-module-3",
    storageKey: "quantum-atlas-v2",
    emblem: "⚛",
    brand: "quantum",
    brandSuffix: "atlas",
    course: "Quantum mechanics",
    qualification: "BSc Physics",
    module: "Module 3",
    subtitle: "Mathematical tools · Module 3",
    description: "Mathematical Tools of Quantum Mechanics",
    exportPrefix: "Quantum-Atlas",
    sourceName: "Module3.pdf",
    sourcePages: 4,
    localOnly: true,
    sections: [
      { id: "A", label: "Part A", title: "Spaces and operators", tag: "FOUNDATIONS", hint: "Linear spaces, inner products, operators" },
      { id: "B", label: "Part B", title: "Inequalities and spectra", tag: "PROOFS", hint: "Schwarz, uncertainty, Hermitian theorems" },
      { id: "C", label: "Part C", title: "Matrices and continuous bases", tag: "REPRESENTATIONS", hint: "Matrices, basis change, x and p" },
    ],
    offlineDownload: "./index.html",
    parentUrl: "/phy/quantum-mechanics/#/study-map",
  },
};
