"""Original DA bridge; intentionally separate from Ross chapters."""
from pathlib import Path
import json
root=Path(__file__).resolve().parents[1]
C=[];W=[];O=[]
NIST='NIST Engineering Statistics Handbook, https://www.itl.nist.gov/div898/handbook/eda/section3/'
def concept(n,sec,title,statement,intuition,trap,q,a,proof=None):
 c=dict(id=f'c.prob.DA.{n}',sec=sec,kind='theorem' if proof else 'definition',tier='core',title=title,oneLine=intuition,statement=statement,intuition=intuition,needs=[],traps=trap if isinstance(trap,list) else [trap],cards=[dict(q=q,a=a,kind='state')],provenance='Original GATE DA supplement; not a Ross section. '+NIST)
 if proof:c['proof']=dict(idea=proof[0],why=proof[1],rungs=[dict(why=x[0],m=x[1],meaning=x[2]) for x in proof[2]],ends=proof[3])
 C.append(c)
def practice(n,title,prompt,solution,trap,value=None,sec=None,options=None,answer=None,concept_num=None):
 c=C[(concept_num or n)-1];s=sec or c['sec'];base=dict(course='prob',sec=s,marks=2,tests=[c['id']],provenance='Original DA practice, not a textbook exercise or past paper.')
 W.append(dict(base,id=f'q.prob.DA.{n}',title=title,prompt=prompt,approach='Identify the sampling model and its assumptions before substituting numbers.',solution=solution,trap=trap,source='Original DA bridge exercise'))
 if value is not None:
  O.append(dict(base,id=f'o.prob.DA.{n}',type='NAT',neg=0,negLabel='0',time=120,prompt=prompt,answer=dict(value=value,tol=.005,dp=3),solution=solution,tested=c['title'],trap=trap,twist=dict(q='Which assumption makes this calculation valid?',a=c['statement'])))
 elif options:
  O.append(dict(base,id=f'o.prob.DA.{n}',type='MCQ',neg=-2/3,negLabel='−2/3',time=120,prompt=prompt,options=[dict(k=k,t=v) for k,v in zip('ABCD',options)],answer=answer,solution=solution,tested=c['title'],trap=trap,twist=dict(q='State the condition for using this result.',a=c['statement'])))
concept(1,'DA.1','Mean, median, mode and standard deviation',r'For observations $x_1,\ldots,x_n$, $\bar x=n^{-1}\sum_i x_i$. Sort the data to find the median (the central value, or average of the two central values). Modes are values with greatest frequency; there may be several. A population median $m$ satisfies $P(X\le m)\ge1/2$ and $P(X\ge m)\ge1/2$. Population standard deviation is $\sigma=\sqrt{\operatorname{Var}(X)}$. Sample variance is $s^2=\sum_i(x_i-\bar x)^2/(n-1)$ and sample standard deviation is $s=\sqrt{s^2}$ for $n>1$. A continuous density mode maximizes the density when such a maximum exists.','Picture the data on a number line: the mean is its balance point, the median is the middle after sorting, and the mode is the most common value. Standard deviation is a typical distance from the mean, measured in the same units as the data.','Population and sample variance have different denominators; a mean need not equal a median or a mode.','Define the sample mean and unbiased sample variance.',r'$\bar x=\sum_i x_i/n$, $s^2=\sum_i(x_i-\bar x)^2/(n-1)$.')
concept(2,'DA.1','Sampling distribution and standard error',r'For iid observations with finite mean $\mu$ and variance $\sigma^2$, $E[\bar X]=\mu$ and $\operatorname{Var}(\bar X)=\sigma^2/n$. Standard error is $\sigma/\sqrt n$, estimated by $s/\sqrt n$. If observations are normal, $\bar X$ is exactly normal; otherwise the CLT supplies a large-sample approximation under its hypotheses.','Imagine taking many samples and calculating the mean each time. The sample means bunch around the true mean, and their standard deviation (the standard error) shrinks as the samples get larger.','Increasing sample size by a factor of four halves standard error; independence is needed for the stated variance.', 'What is the standard error of an iid sample mean?',r'$\sigma/\sqrt n$; estimate it by $s/\sqrt n$ when needed.',('Use linearity and variance of an independent sum.','Averaging rescales the sum by 1/n.',[('Apply linearity.',r'$E[\bar X]=\frac1n\sum_i\mu=\mu$','Each observation contributes the same mean.'),('Use independence to remove covariance terms.',r'$\operatorname{Var}(\bar X)=\frac1{n^2}\sum_i\sigma^2=\sigma^2/n$','Correlated data need the covariance terms instead.')],'This explains the square-root sample-size law.'))
concept(3,'DA.1','Chi-squared distribution',r'If $Z_1,\ldots,Z_\nu$ are independent standard normal variables, $V=\sum_i Z_i^2\sim\chi^2_\nu$, where $\nu$ is a positive integer. Its density is $v^{\nu/2-1}e^{-v/2}/[2^{\nu/2}\Gamma(\nu/2)]$ for $v>0$; it is Gamma(shape $\nu/2$, rate $1/2$). $E[V]=\nu$ and $\operatorname{Var}(V)=2\nu$. Independent chi-squared variables add their degrees of freedom.','Start with independent standard-normal scores and square each one. The squares are never negative, so their total measures how large the combined departures are; this total has a chi-squared distribution.','Chi-squared is asymmetric and supported on nonnegative values; do not use symmetric critical values.', 'Define a chi-squared variable and give its mean and variance.',r'$V=\sum_{i=1}^{\nu} Z_i^2$ for independent $N(0,1)$ variables; $E[V]=\nu$, $\operatorname{Var}(V)=2\nu$.')
concept(4,'DA.1','Student t distribution',r'If $Z\sim N(0,1)$ and $V\sim\chi^2_\nu$ are independent, then $T=Z/\sqrt{V/\nu}\sim t_\nu$. Its density is $\Gamma((\nu+1)/2)[1+t^2/\nu]^{-(\nu+1)/2}/[\sqrt{\nu\pi}\Gamma(\nu/2)]$. It is symmetric with heavier tails than normal; mean is zero for $\nu>1$, variance $\nu/(\nu-2)$ for $\nu>2$. For a normal iid sample, $(\bar X-\mu)/(S/\sqrt n)\sim t_{n-1}$.','A t score is like a z score, except its spread is estimated from the sample. That extra uncertainty makes extreme scores more common; with more data, the t curve gets closer to the standard normal curve.','Unknown sigma alone does not make a small-sample t calculation exact: the normal-sample model is essential.', 'What ratio defines t, and which independence condition is required?',r'$Z/\sqrt{V/\nu}$ with $Z\sim N(0,1)$ independent of $V\sim\chi^2_\nu$.')
concept(5,'DA.2','Confidence interval meaning and known-variance mean interval',r'A $(1-\alpha)$ confidence procedure $[L(X),U(X)]$ satisfies $P_\theta(L(X)\le\theta\le U(X))=1-\alpha$ under its model (or approximately for an asymptotic procedure). For iid normal data with known $\sigma$, the two-sided mean interval is $\bar X\pm z_{1-\alpha/2}\sigma/\sqrt n$, where $P(Z\le z_q)=q$. For nonnormal iid data it is a CLT approximation, not an exact finite-sample assertion.','A confidence interval is made by a rule that works well over many repeated samples. A 95% rule catches the true fixed value about 95 times out of 100; after one sample, its two endpoints are fixed.', 'A realized frequentist interval does not assign 95% probability to the fixed parameter. Use alpha/2 in each tail for a two-sided interval.','State the known-sigma normal mean confidence interval.',r'$\bar X\pm z_{1-\alpha/2}\sigma/\sqrt n$.',('Invert a standardized probability statement.','Solve both inequalities for the unknown mean.',[('Standardize the mean.',r'$P(-z_{1-\alpha/2}\le(\bar X-\mu)/(\sigma/\sqrt n)\le z_{1-\alpha/2})=1-\alpha$','The normal pivot has a parameter-free distribution.'),('Rearrange the inequalities.',r'$P(\bar X-z_{1-\alpha/2}\sigma/\sqrt n\le\mu\le\bar X+z_{1-\alpha/2}\sigma/\sqrt n)=1-\alpha$','The random endpoints give repeated-sample coverage.')],'The confidence level belongs to the procedure.'))
concept(6,'DA.2','Unknown-variance mean interval',r'For an iid normal sample of size $n>1$ with unknown variance, an exact two-sided interval for $\mu$ is $\bar X\pm t_{n-1,1-\alpha/2}S/\sqrt n$. Here $S^2$ uses denominator $n-1$ and $P(t_\nu\le t_{\nu,q})=q$. This is not an exact small-sample interval for arbitrary distributions.','When the population spread is unknown, use the sample spread. Because that estimate can wobble, use a t cutoff that leaves a little more room than the normal cutoff.','Use n−1 degrees of freedom and a t quantile, rather than replacing sigma with s while keeping a z quantile for an exact small-sample result.','State the exact normal-sample mean interval with unknown variance.',r'$\bar X\pm t_{n-1,1-\alpha/2}S/\sqrt n$.')
concept(7,'DA.2','Variance confidence interval',r'For iid normal observations, $V=(n-1)S^2/\sigma^2\sim\chi^2_{n-1}$. With lower-tail quantiles $\chi^2_{\nu,q}$, a two-sided interval for variance is $[(n-1)S^2/\chi^2_{n-1,1-\alpha/2},\;(n-1)S^2/\chi^2_{n-1,\alpha/2}]$. Square-root its endpoints for a standard-deviation interval.','A chi-squared score compares the sample spread with a proposed population spread. Solving the comparison for the unknown spread puts each cutoff underneath it, so the larger cutoff gives the smaller endpoint.','The larger chi-square quantile goes in the lower endpoint; normality is required for the exact pivot.','Which chi-square quantile appears in the lower variance endpoint?',r'The upper lower-tail quantile $\chi^2_{n-1,1-\alpha/2}$.')
concept(8,'DA.2','Proportion intervals and precision',r'For iid Bernoulli trials, $\hat p=X/n$ with $X\sim\operatorname{Bin}(n,p)$. A large-sample Wald interval is $\hat p\pm z_{1-\alpha/2}\sqrt{\hat p(1-\hat p)/n}$, requiring both success and failure counts sufficiently large; it is unreliable near 0 or 1 and for small n. Planning for half-width $\epsilon$ uses $n\ge z_{1-\alpha/2}^2p(1-p)/\epsilon^2$, rounded up; without a prior p, use $p(1-p)\le1/4$.','A sample proportion is the fraction of successes in a poll or experiment. Larger samples make that fraction steadier, but to make the margin of error half as wide you need about four times as many observations.','Do not call the Wald interval exact; its endpoints can fall outside [0,1], exposing a poor approximation.', 'What is the conservative sample-size bound for a proportion half-width epsilon?',r'$n\ge z_{1-\alpha/2}^2/(4\epsilon^2)$, rounded upward.')
concept(9,'DA.3','Null hypothesis, p-value and errors',r'A test chooses a rejection region under $H_0$. Type I error rejects a true null, controlled at level $\alpha$; Type II error fails to reject a false null, with probability $\beta$ depending on the alternative. Power is $1-\beta$. A p-value is the probability, computed under $H_0$, of a test statistic at least as extreme as observed according to the specified alternative. Reject when p-value $\le\alpha$ by the chosen convention.','A hypothesis test asks: if the starting claim were true, would results like these be unusual? A small p-value says “unusual under that claim”; it does not tell us the chance that the claim itself is true.','Failure to reject is not proof of equality. Choose the alternative before seeing results; p-value is not P(H0 | data).','Define a p-value, Type I error and power.', 'p-value is a null-model tail probability for at least the observed extremeness; Type I error rejects a true null; power is the rejection probability at a specified alternative.')
concept(10,'DA.3','z-test and t-test for a mean',r'For $H_0:\mu=\mu_0$, known-sigma normal-sample statistic is $Z=(\bar X-\mu_0)/(\sigma/\sqrt n)$. With unknown sigma in an iid normal sample, $T=(\bar X-\mu_0)/(S/\sqrt n)\sim t_{n-1}$ under $H_0$. Two-sided tests reject for $|Z|>z_{1-\alpha/2}$ or $|T|>t_{n-1,1-\alpha/2}$; upper/lower alternatives use the corresponding single tail. The two-sided mean interval excludes $\mu_0$ exactly when the matching test rejects, aside from boundary conventions.','Subtract the value claimed by the null, then count how many standard errors away the sample result lies. Compare that distance with a z or t curve, using the tail named by the question.','Use the hypothesized null mean in the numerator and select tails from H1, not from the observed sign.', 'Give the one-sample t statistic and its null degrees of freedom.',r'$T=(\bar X-\mu_0)/(S/\sqrt n)$, with $n-1$ degrees of freedom for iid normal data.')
concept(11,'DA.3','Chi-squared tests: variance, goodness of fit and independence',r'For a normal-sample variance null $\sigma^2=\sigma_0^2$, use $(n-1)S^2/\sigma_0^2\sim\chi^2_{n-1}$ and the specified tail(s). Goodness of fit uses $\sum_i(O_i-E_i)^2/E_i$, asymptotically $\chi^2_{k-1-r}$ when k categories have positive expected counts and r parameters are estimated under regular conditions. For an $a\times b$ independence table, $E_{ij}=O_{i+}O_{+j}/n$ and degrees of freedom $(a-1)(b-1)$. Count tests reject in the upper tail; sparse cells may invalidate the approximation.','First ask what counts the null claim predicts. The chi-squared score adds up how far the actual counts miss those predictions; a large total is evidence against the claim.','Do not confuse the exact variance pivot with approximate categorical tests. Subtract fitted parameters from goodness-of-fit degrees of freedom.','State the independence-table expected count and degrees of freedom.',r'$E_{ij}=O_{i+}O_{+j}/n$, $\nu=(a-1)(b-1)$.')
concept(12,'DA.3','Two samples and paired measurements',r'For independent normal samples with a common unknown variance, $S_p^2=[(n_1-1)S_1^2+(n_2-1)S_2^2]/(n_1+n_2-2)$ and $T=(\bar X_1-\bar X_2-\delta_0)/[S_p\sqrt{1/n_1+1/n_2}]$ has $n_1+n_2-2$ degrees of freedom under the difference null. Without equal variances, use Welch standard error $\sqrt{S_1^2/n_1+S_2^2/n_2}$ and approximate Welch degrees of freedom. For paired measurements, form each difference $D_i$ and perform a one-sample test on iid normal differences.','For matched people or before-and-after measurements, compare each pair directly. For two separate groups, compare their averages; combine their spread estimates only if equal population spreads are a reasonable assumption.','Do not treat paired before/after observations as independent samples or pool variances without justification.', 'How should paired data be reduced for a mean-difference test?',r'Form $D_i=X_i-Y_i$, then use $T=(\bar D-\delta_0)/(S_D/\sqrt n)$ with $n-1$ degrees of freedom for iid normal differences.')
concept(13,'DA.2','Confidence interval for a difference of means',r'For two independent normal samples with equal unknown variances, a $(1-\alpha)$ interval for $\mu_1-\mu_2$ is $(\bar X_1-\bar X_2)\pm t_{n_1+n_2-2,1-\alpha/2}S_p\sqrt{1/n_1+1/n_2}$. For paired data, apply the one-sample t interval to the within-pair differences. Without equal variances, use a Welch interval with approximate degrees of freedom.','To compare two groups, start with the observed difference in their averages and add a margin for sampling wobble. Matched pairs are handled by first finding each pair’s difference; separate groups need an extra equal-spread assumption for the pooled formula.',['The pooled interval assumes independent normal samples and equal population variances; pairing calls for differences instead.'],'State the pooled two-sample t interval for a difference of means.',r'$(\bar X_1-\bar X_2)\pm t_{n_1+n_2-2,1-\alpha/2}S_p\sqrt{1/n_1+1/n_2}$.')
concept(14,'DA.3','Large-sample z-tests for proportions',r'For iid Bernoulli trials, under $H_0:p=p_0$, the one-proportion statistic is $Z=(\hat p-p_0)/\sqrt{p_0(1-p_0)/n}$, approximately standard normal when null expected success and failure counts are sufficiently large. For two independent samples under $H_0:p_1=p_2$, use the pooled estimate $\hat p=(X_1+X_2)/(n_1+n_2)$ in the standard error $\sqrt{\hat p(1-\hat p)(1/n_1+1/n_2)}$.','When the data are success/failure counts, compare the observed fraction with the fraction claimed by the null. For two groups, pool their successes only to estimate the shared fraction assumed by the null; the resulting z score is a large-sample approximation.',['These are large-sample tests, not exact small-sample procedures.','For a two-sample test, use the pooled fraction in the null standard error; separate sample fractions belong in an unpooled confidence interval.'],'State the null standard error for a two-proportion z-test.',r'$\sqrt{\hat p(1-\hat p)(1/n_1+1/n_2)}$, where $\hat p=(X_1+X_2)/(n_1+n_2)$ under $H_0:p_1=p_2$.')
practice(1,'Summaries','For the observations 1, 2, 2, 5, 10, find the sample median.',r'The sorted middle observation is 2. Mean is 4; mode is 2. Squared deviations sum to 54, so sample variance is 54/4=13.5.','The mean of 4 is not the median.',2)
practice(2,'Standard error','For iid observations with standard deviation 12 and n=36, find the standard error of the sample mean.',r'$12/\sqrt{36}=2$.','Divide by square root of n, not n.',2)
practice(3,'Chi-square variance',r'Let $V=\sum_{i=1}^5Z_i^2$ for independent standard normal variables. Find Var(V).',r'$V\sim\chi^2_5$, so variance is $2\cdot5=10$.','Mean is 5; variance is 10.',10)
practice(4,'t variance',r'Find the variance of $T\sim t_6$.',r'$6/(6-2)=1.5$.','The variance exists only above 2 degrees of freedom.',1.5)
practice(5,'Normal mean interval','An iid normal sample has n=100, mean 20 and known sigma=5. Use z(0.975)=1.96. Find the upper endpoint of the 95% mean interval.',r'Standard error is 0.5. The interval is $20\pm0.98=[19.02,20.98]$.','Use standard error rather than sigma.',20.98)
practice(6,'t mean interval','An iid normal sample has n=9, mean 15 and s=3. Use t(8,0.975)=2.306. Find the lower endpoint of the 95% mean interval.',r'$15-2.306(3/3)=12.694$.','There are 8 degrees of freedom, not 9.',12.694)
practice(7,'Variance interval','For a normal sample with n=11 and s²=4, the relevant chi-square lower/upper quantiles are 3.247 and 20.483. Find the lower endpoint of the two-sided variance interval.',r'$10\cdot4/20.483\approx1.953$. The upper endpoint is $40/3.247\approx12.319$.','Use the larger quantile in the lower endpoint.',40/20.483)
practice(8,'Precision planning','Using z=1.96 and the worst-case proportion, what sample size is needed for a planned half-width at most 0.05?',r'$n\ge1.96^2/(4\cdot0.05^2)=384.16$. Round up to 385.','Rounding down violates the planned bound.',385)
practice(9,'Interpret a p-value','A prespecified test returns p=0.03. At significance level 0.05, which conclusion is justified?','Reject the null at the chosen significance level. This does not give the probability that the null is false.','A p-value is a null-model tail probability.',options=['The null is true with probability 0.03','Reject the null at level 0.05','Accept the null with certainty','The test has power 0.97'],answer='B')
practice(10,'Mean test','For an iid normal sample, n=25, mean=52, s=5. Under H0: mean=50, find the one-sample t statistic.',r'$T=(52-50)/(5/5)=2$, with 24 degrees of freedom. Use the chosen alternative to decide the tail.','The statistic alone does not specify a rejection decision.',2)
practice(11,'Independence counts','A 2×2 count table has rows (30,20) and (10,40). Find the chi-square independence statistic.',r'Row totals are 50 and 50; column totals are 40 and 60. Expected rows are (20,30) and (20,30). Statistic is $100/20+100/30+100/20+100/30=16.6667$, with one degree of freedom.','Expected counts use row and column totals, not equal cells.',50/3)
practice(12,'Pooled degrees of freedom','Two independent normal samples of sizes 8 and 12 have equal unknown population variance. What degrees of freedom apply to the pooled two-sample t test?',r'$8+12-2=18$. With unequal variances, the pooled exact model is invalid; use Welch instead.','Subtract two because two sample means have been estimated.',18)
practice(13,'Two-sample mean interval',r'Two independent normal samples have $n_1=n_2=10$, means 12 and 10, and standard deviations $s_1=s_2=2$. Assume equal population variances and use $t_{18,0.975}=2.101$. Find the lower endpoint of the 95% interval for $\mu_1-\mu_2$.',r'The pooled standard deviation is 2 and the standard error is $2\sqrt{1/10+1/10}=0.8944$. The interval is $2\pm2.101(0.8944)$, so its lower endpoint is about 0.121.','Use the pooled t interval only under independent normal samples with equal unknown variances.',0.121)
practice(14,'One-proportion z statistic',r'In 100 independent trials, 60 are successes. Under $H_0:p=0.5$, find the one-proportion z statistic.',r'$\hat p=0.60$ and the null standard error is $\sqrt{0.5(0.5)/100}=0.05$. Thus $Z=(0.60-0.50)/0.05=2$.','Use the null value in the standard error; this is a large-sample approximation.',2)
practice(15,'Chi-square goodness of fit',r'A four-outcome model predicts equal probabilities. Observed counts are 6, 14, 10, and 10. Find Pearson’s chi-square statistic.',r'With total 40, each expected count is 10. Thus $X^2=(6-10)^2/10+(14-10)^2/10=3.2$; the two matching counts contribute zero. With no fitted parameters, the reference degrees of freedom are $4-1=3$.','Expected counts come from the null model; use the observed total to obtain them.',3.2,sec='DA.3',concept_num=11)
practice(16,'Chi-square variance statistic',r'A normal sample has size 10 and sample variance 4. Under $H_0:\sigma^2=2$, find the chi-square test statistic.',r'$X^2=(n-1)S^2/\sigma_0^2=9(4)/2=18$, with 9 degrees of freedom under the null.','The exact variance pivot requires a normal population.',18,sec='DA.3',concept_num=11)
practice(17,'Sample standard deviation',r'For the data 1, 2, 3, 4, 5, find the sample standard deviation using denominator $n-1$.',r'The mean is 3 and the squared deviations sum to 10. Thus $s^2=10/4=2.5$ and $s=\sqrt{2.5}\approx1.581$.','Use denominator n−1 for the sample variance here, then take its square root.',1.581,sec='DA.1',concept_num=1)
practice(18,'Known-variance mean z statistic',r'An iid normal sample has size 36, mean 52, and known population standard deviation 6. Under $H_0:\mu=50$, find the one-sample z statistic.',r'The standard error is $6/\sqrt{36}=1$. Therefore $Z=(52-50)/1=2$ under the null.', 'Use z when the population standard deviation is known; the given normal model makes the sampling law exact.',2,sec='DA.3',concept_num=10)
practice(19,'Pooled two-sample t statistic',r'Two independent normal samples have $n_1=n_2=10$, means 12 and 9, and standard deviations 2 in each group. Assume equal population variances and test $H_0:\mu_1-\mu_2=0$. Find the pooled t statistic.',r'The pooled standard deviation is 2. The standard error is $2\sqrt{1/10+1/10}=0.8944$, so $T=3/0.8944\approx3.354$ with 18 degrees of freedom.', 'Pooling requires independent normal samples with equal population variances.',3.354,sec='DA.3',concept_num=12)
practice(20,'Paired t statistic',r'Four matched before-and-after differences are 2, 4, 3, and 5. Under a normal-differences model and $H_0:\mu_D=0$, find the paired t statistic.',r'The differences have mean 3.5 and sample variance $5/3$, so $s_D=\sqrt{5/3}$. Thus $T=3.5/(\sqrt{5/3}/\sqrt4)\approx5.422$ with 3 degrees of freedom.', 'Analyze the four within-pair differences; do not treat the two measurements in each pair as independent.',5.422,sec='DA.3',concept_num=12)
practice(21,'Two-proportion z statistic',r'Two independent samples have 60 successes in 100 trials and 40 successes in 100 trials. Under $H_0:p_1=p_2$, find the pooled two-proportion z statistic.',r'The pooled estimate is $100/200=0.5$. The null standard error is $\sqrt{0.5(0.5)(1/100+1/100)}=0.07071$. Therefore $Z=(0.60-0.40)/0.07071\approx2.828$.','Pool successes to estimate the shared null proportion; this is a large-sample z approximation.',2.828,sec='DA.3',concept_num=14)
for kind,glob,rows in [('concepts','CONCEPTS',C),('written','QUESTIONS',W),('objective','OBJECTIVE',O)]:
 (root/f'data/inference.{kind}.js').write_text(f'{glob}.push(\n'+',\n'.join(json.dumps(c,ensure_ascii=False,indent=2) for c in rows)+'\n);\n')
print(len(C),len(W),len(O))
