"""Original DA bridge; intentionally separate from Ross chapters."""
from pathlib import Path
import json
root=Path(__file__).resolve().parents[1]
C=[];W=[];O=[]
NIST='NIST Engineering Statistics Handbook, https://www.itl.nist.gov/div898/handbook/eda/section3/'
def concept(n,sec,title,statement,intuition,trap,q,a,proof=None):
 c=dict(id=f'c.prob.DA.{n}',sec=sec,kind='theorem' if proof else 'definition',tier='core',title=title,oneLine=intuition,statement=statement,intuition=intuition,needs=[],traps=[trap],cards=[dict(q=q,a=a,kind='state')],provenance='Original GATE DA supplement; not a Ross section. '+NIST)
 if proof:c['proof']=dict(idea=proof[0],why=proof[1],rungs=[dict(why=x[0],m=x[1],meaning=x[2]) for x in proof[2]],ends=proof[3])
 C.append(c)
def practice(n,title,prompt,solution,trap,value=None,sec=None,options=None,answer=None):
 c=C[n-1];s=sec or c['sec'];base=dict(course='prob',sec=s,marks=2,tests=[c['id']],provenance='Original DA practice, not a textbook exercise or past paper.')
 W.append(dict(base,id=f'q.prob.DA.{n}',title=title,prompt=prompt,approach='Identify the sampling model and its assumptions before substituting numbers.',solution=solution,trap=trap,source='Original DA bridge exercise'))
 if value is not None:
  O.append(dict(base,id=f'o.prob.DA.{n}',type='NAT',neg=0,negLabel='0',time=120,prompt=prompt,answer=dict(value=value,tol=.005,dp=3),solution=solution,tested=c['title'],trap=trap,twist=dict(q='Which assumption makes this calculation valid?',a=c['statement'])))
 elif options:
  O.append(dict(base,id=f'o.prob.DA.{n}',type='MCQ',neg=-2/3,negLabel='−2/3',time=120,prompt=prompt,options=[dict(k=k,t=v) for k,v in zip('ABCD',options)],answer=answer,solution=solution,tested=c['title'],trap=trap,twist=dict(q='State the condition for using this result.',a=c['statement'])))
concept(1,'DA.1','Mean, median, mode and standard deviation',r'For observations $x_1,\ldots,x_n$, $\bar x=n^{-1}\sum_i x_i$. Sort the data to find the median (the central value, or average of the two central values). Modes are values with greatest frequency; there may be several. A population median $m$ satisfies $P(X\le m)\ge1/2$ and $P(X\ge m)\ge1/2$. Population standard deviation is $\sqrt{\operatorname{Var}(X)}$. Sample variance is $s^2=\sum_i(x_i-\bar x)^2/(n-1)$ for $n>1$. A continuous density mode maximizes the density when such a maximum exists.','Mean balances the data; median splits ordered mass; mode identifies the most concentrated value. Standard deviation measures spread in the original units.','Population and sample variance have different denominators; a mean need not equal a median or a mode.','Define the sample mean and unbiased sample variance.',r'$\bar x=\sum_i x_i/n$, $s^2=\sum_i(x_i-\bar x)^2/(n-1)$.')
concept(2,'DA.1','Sampling distribution and standard error',r'For iid observations with finite mean $\mu$ and variance $\sigma^2$, $E[\bar X]=\mu$ and $\operatorname{Var}(\bar X)=\sigma^2/n$. Standard error is $\sigma/\sqrt n$, estimated by $s/\sqrt n$. If observations are normal, $\bar X$ is exactly normal; otherwise the CLT supplies a large-sample approximation under its hypotheses.','An estimator varies across repeated samples. Its standard error concerns uncertainty in the estimator, whereas standard deviation concerns variability of individual observations.','Increasing sample size by a factor of four halves standard error; independence is needed for the stated variance.', 'What is the standard error of an iid sample mean?',r'$\sigma/\sqrt n$; estimate it by $s/\sqrt n$ when needed.',('Use linearity and variance of an independent sum.','Averaging rescales the sum by 1/n.',[('Apply linearity.',r'$E[\bar X]=\frac1n\sum_i\mu=\mu$','Each observation contributes the same mean.'),('Use independence to remove covariance terms.',r'$\operatorname{Var}(\bar X)=\frac1{n^2}\sum_i\sigma^2=\sigma^2/n$','Correlated data need the covariance terms instead.')],'This explains the square-root sample-size law.'))
concept(3,'DA.1','Chi-squared distribution',r'If $Z_1,\ldots,Z_\nu$ are independent standard normal variables, $V=\sum_i Z_i^2\sim\chi^2_\nu$, where $\nu$ is a positive integer. Its density is $v^{\nu/2-1}e^{-v/2}/[2^{\nu/2}\Gamma(\nu/2)]$ for $v>0$; it is Gamma(shape $\nu/2$, rate $1/2$). $E[V]=\nu$ and $\operatorname{Var}(V)=2\nu$. Independent chi-squared variables add their degrees of freedom.','Squared standardized fluctuations add into a positive measure of total deviation.','Chi-squared is asymmetric and supported on nonnegative values; do not use symmetric critical values.', 'Define a chi-squared variable and give its mean and variance.',r'$V=\sum_{i=1}^{\nu} Z_i^2$ for independent $N(0,1)$ variables; $E[V]=\nu$, $\operatorname{Var}(V)=2\nu$.')
concept(4,'DA.1','Student t distribution',r'If $Z\sim N(0,1)$ and $V\sim\chi^2_\nu$ are independent, then $T=Z/\sqrt{V/\nu}\sim t_\nu$. Its density is $\Gamma((\nu+1)/2)[1+t^2/\nu]^{-(\nu+1)/2}/[\sqrt{\nu\pi}\Gamma(\nu/2)]$. It is symmetric with heavier tails than normal; mean is zero for $\nu>1$, variance $\nu/(\nu-2)$ for $\nu>2$. For a normal iid sample, $(\bar X-\mu)/(S/\sqrt n)\sim t_{n-1}$.','Estimating the denominator adds uncertainty; heavy tails account for it. As degrees of freedom grow, t approaches standard normal.','Unknown sigma alone does not make a small-sample t calculation exact: the normal-sample model is essential.', 'What ratio defines t, and which independence condition is required?',r'$Z/\sqrt{V/\nu}$ with $Z\sim N(0,1)$ independent of $V\sim\chi^2_\nu$.')
concept(5,'DA.2','Confidence interval meaning and known-variance mean interval',r'A $(1-\alpha)$ confidence procedure $[L(X),U(X)]$ satisfies $P_\theta(L(X)\le\theta\le U(X))=1-\alpha$ under its model (or approximately for an asymptotic procedure). For iid normal data with known $\sigma$, the two-sided mean interval is $\bar X\pm z_{1-\alpha/2}\sigma/\sqrt n$, where $P(Z\le z_q)=q$. For nonnormal iid data it is a CLT approximation, not an exact finite-sample assertion.','The procedure captures the fixed parameter in a stated fraction of repeated samples. Once observed, the endpoints are fixed.', 'A realized frequentist interval does not assign 95% probability to the fixed parameter. Use alpha/2 in each tail for a two-sided interval.','State the known-sigma normal mean confidence interval.',r'$\bar X\pm z_{1-\alpha/2}\sigma/\sqrt n$.',('Invert a standardized probability statement.','Solve both inequalities for the unknown mean.',[('Standardize the mean.',r'$P(-z_{1-\alpha/2}\le(\bar X-\mu)/(\sigma/\sqrt n)\le z_{1-\alpha/2})=1-\alpha$','The normal pivot has a parameter-free distribution.'),('Rearrange the inequalities.',r'$P(\bar X-z_{1-\alpha/2}\sigma/\sqrt n\le\mu\le\bar X+z_{1-\alpha/2}\sigma/\sqrt n)=1-\alpha$','The random endpoints give repeated-sample coverage.')],'The confidence level belongs to the procedure.'))
concept(6,'DA.2','Unknown-variance mean interval',r'For an iid normal sample of size $n>1$ with unknown variance, an exact two-sided interval for $\mu$ is $\bar X\pm t_{n-1,1-\alpha/2}S/\sqrt n$. Here $S^2$ uses denominator $n-1$ and $P(t_\nu\le t_{\nu,q})=q$. This is not an exact small-sample interval for arbitrary distributions.','Replace the known population spread with an estimate and widen the critical value to account for that estimation.','Use n−1 degrees of freedom and a t quantile, rather than replacing sigma with s while keeping a z quantile for an exact small-sample result.','State the exact normal-sample mean interval with unknown variance.',r'$\bar X\pm t_{n-1,1-\alpha/2}S/\sqrt n$.')
concept(7,'DA.2','Variance confidence interval',r'For iid normal observations, $V=(n-1)S^2/\sigma^2\sim\chi^2_{n-1}$. With lower-tail quantiles $\chi^2_{\nu,q}$, a two-sided interval for variance is $[(n-1)S^2/\chi^2_{n-1,1-\alpha/2},\;(n-1)S^2/\chi^2_{n-1,\alpha/2}]$. Square-root its endpoints for a standard-deviation interval.','The unknown variance occurs in the denominator of a positive pivot, so solving reverses the reciprocal order of the critical values.','The larger chi-square quantile goes in the lower endpoint; normality is required for the exact pivot.','Which chi-square quantile appears in the lower variance endpoint?',r'The upper lower-tail quantile $\chi^2_{n-1,1-\alpha/2}$.')
concept(8,'DA.2','Proportion intervals and precision',r'For iid Bernoulli trials, $\hat p=X/n$ with $X\sim\operatorname{Bin}(n,p)$. A large-sample Wald interval is $\hat p\pm z_{1-\alpha/2}\sqrt{\hat p(1-\hat p)/n}$, requiring both success and failure counts sufficiently large; it is unreliable near 0 or 1 and for small n. Planning for half-width $\epsilon$ uses $n\ge z_{1-\alpha/2}^2p(1-p)/\epsilon^2$, rounded up; without a prior p, use $p(1-p)\le1/4$.','Intervals shrink at the square-root rate, so doubling precision takes about four times as much data.','Do not call the Wald interval exact; its endpoints can fall outside [0,1], exposing a poor approximation.', 'What is the conservative sample-size bound for a proportion half-width epsilon?',r'$n\ge z_{1-\alpha/2}^2/(4\epsilon^2)$, rounded upward.')
concept(9,'DA.3','Null hypothesis, p-value and errors',r'A test chooses a rejection region under $H_0$. Type I error rejects a true null, controlled at level $\alpha$; Type II error fails to reject a false null, with probability $\beta$ depending on the alternative. Power is $1-\beta$. A p-value is the probability, computed under $H_0$, of a test statistic at least as extreme as observed according to the specified alternative. Reject when p-value $\le\alpha$ by the chosen convention.','A test asks whether the observation is unusually incompatible with the null model; it does not estimate the probability the null is true.','Failure to reject is not proof of equality. Choose the alternative before seeing results; p-value is not P(H0 | data).','Define a p-value, Type I error and power.', 'p-value is a null-model tail probability for at least the observed extremeness; Type I error rejects a true null; power is the rejection probability at a specified alternative.')
concept(10,'DA.3','z-test and t-test for a mean',r'For $H_0:\mu=\mu_0$, known-sigma normal-sample statistic is $Z=(\bar X-\mu_0)/(\sigma/\sqrt n)$. With unknown sigma in an iid normal sample, $T=(\bar X-\mu_0)/(S/\sqrt n)\sim t_{n-1}$ under $H_0$. Two-sided tests reject for $|Z|>z_{1-\alpha/2}$ or $|T|>t_{n-1,1-\alpha/2}$; upper/lower alternatives use the corresponding single tail. The two-sided mean interval excludes $\mu_0$ exactly when the matching test rejects, aside from boundary conventions.','A difference is measured in standard errors, then compared with the relevant null sampling distribution.','Use the hypothesized null mean in the numerator and select tails from H1, not from the observed sign.', 'Give the one-sample t statistic and its null degrees of freedom.',r'$T=(\bar X-\mu_0)/(S/\sqrt n)$, with $n-1$ degrees of freedom for iid normal data.')
concept(11,'DA.3','Chi-squared tests: variance, goodness of fit and independence',r'For a normal-sample variance null $\sigma^2=\sigma_0^2$, use $(n-1)S^2/\sigma_0^2\sim\chi^2_{n-1}$ and the specified tail(s). Goodness of fit uses $\sum_i(O_i-E_i)^2/E_i$, asymptotically $\chi^2_{k-1-r}$ when k categories have positive expected counts and r parameters are estimated under regular conditions. For an $a\times b$ independence table, $E_{ij}=O_{i+}O_{+j}/n$ and degrees of freedom $(a-1)(b-1)$. Count tests reject in the upper tail; sparse cells may invalidate the approximation.','Expected counts come from the null model. Squared relative discrepancies measure how far the observed table departs from it.','Do not confuse the exact variance pivot with approximate categorical tests. Subtract fitted parameters from goodness-of-fit degrees of freedom.','State the independence-table expected count and degrees of freedom.',r'$E_{ij}=O_{i+}O_{+j}/n$, $\nu=(a-1)(b-1)$.')
concept(12,'DA.3','Two samples and paired measurements',r'For independent normal samples with a common unknown variance, $S_p^2=[(n_1-1)S_1^2+(n_2-1)S_2^2]/(n_1+n_2-2)$ and $T=(\bar X_1-\bar X_2-\delta_0)/[S_p\sqrt{1/n_1+1/n_2}]$ has $n_1+n_2-2$ degrees of freedom under the difference null. Without equal variances, use Welch standard error $\sqrt{S_1^2/n_1+S_2^2/n_2}$ and approximate Welch degrees of freedom. For paired measurements, form each difference $D_i$ and perform a one-sample test on iid normal differences.','Pairing and pooling answer different modelling questions. Pairing retains within-pair dependence; pooling assumes equal population variances.','Do not treat paired before/after observations as independent samples or pool variances without justification.', 'How should paired data be reduced for a mean-difference test?',r'Form $D_i=X_i-Y_i$, then use $T=(\bar D-\delta_0)/(S_D/\sqrt n)$ with $n-1$ degrees of freedom for iid normal differences.')
practice(1,'Summaries','For the observations 1, 2, 2, 5, 10, find the sample median.',r'The sorted middle observation is 2. Mean is 4; mode is 2. Squared deviations sum to 54, so sample variance is 54/4=13.5.','The mean of 4 is not the median.',2)
practice(2,'Standard error','For iid observations with standard deviation 12 and n=36, find the standard error of the sample mean.',r'$12/\sqrt{36}=2$.','Divide by square root of n, not n.',2)
practice(3,'Chi-square variance',r'Let $V=\sum_{i=1}^5Z_i^2$ for independent standard normal variables. Find Var(V).',r'$V\sim\chi^2_5$, so variance is $2\cdot5=10$.','Mean is 5; variance is 10.',10)
practice(4,'t variance',r'Find the variance of $T\sim t_6$.',r'$6/(6-2)=1.5$.','The variance exists only above 2 degrees of freedom.',1.5)
practice(5,'Normal mean interval','An iid normal sample has n=100, mean 20 and known sigma=5. Use z(0.975)=1.96. Find the upper endpoint of the 95% mean interval.',r'Standard error is 0.5. The interval is $20\pm0.98=[19.02,20.98]$.','Use standard error rather than sigma.',20.98)
practice(6,'t mean interval','An iid normal sample has n=9, mean 15 and s=3. Use t(8,0.975)=2.306. Find the lower endpoint of the 95% mean interval.',r'$15-2.306(3/3)=12.694$.','There are 8 degrees of freedom, not 9.',12.694)
practice(7,'Variance interval','For a normal sample with n=11 and s²=4, the relevant chi-square lower/upper quantiles are 3.247 and 20.483. Find the lower endpoint of the two-sided variance interval.',r'$10\cdot4/20.483\approx1.953$. The upper endpoint is $40/3.247\approx12.319$.','Use the larger quantile in the lower endpoint.',40/20.483)
practice(8,'Precision planning','Using z=1.96 and the worst-case proportion, what sample size is needed for a planned half-width at most 0.05?',r'$n\ge1.96^2/(4\cdot0.05^2)=384.16$. Round up to 385.','Rounding down violates the planned bound.',385)
practice(9,'Interpret a p-value','A prespecified test returns p=0.03. At significance level 0.05, which conclusion is justified?','Reject the null at the chosen significance level. This does not give the probability that the null is false.','A p-value is a null-model tail probability.',options=['The null is true with probability 0.03','Reject the null at level 0.05','Accept the null with certainty','The test has power 0.97'],answer='B')
practice(10,'Mean test','For an iid normal sample, n=25, mean=52, s=5. Under H0: mean=50, find the one-sample t statistic.',r'$T=(52-50)/(5/5)=2$, with 24 degrees of freedom. Use the chosen alternative to decide the tail.','The statistic alone does not specify a rejection decision.',2)
practice(11,'Independence counts','A 2×2 count table has rows (30,20) and (10,40). Find the chi-square independence statistic.',r'Row totals are 50 and 50; column totals are 40 and 60. Expected rows are (20,30) and (20,30). Statistic is $100/20+100/30+100/20+100/30=16.6667$, with one degree of freedom.','Expected counts use row and column totals, not equal cells.',50/3)
practice(12,'Pooled degrees of freedom','Two independent normal samples of sizes 8 and 12 have equal unknown population variance. What degrees of freedom apply to the pooled two-sample t test?',r'$8+12-2=18$. With unequal variances, the pooled exact model is invalid; use Welch instead.','Subtract two because two sample means have been estimated.',18)
for kind,glob,rows in [('concepts','CONCEPTS',C),('written','QUESTIONS',W),('objective','OBJECTIVE',O)]:
 (root/f'data/inference.{kind}.js').write_text(f'{glob}.push(\n'+',\n'.join(json.dumps(c,ensure_ascii=False,indent=2) for c in rows)+'\n);\n')
print(len(C),len(W),len(O))
