# Module 8: Limit Theorems (13 concepts)
# Explains formal mathematical statement, mathematical terms, and reason behind each statement.

STATEMENTS_CH08 = {
    'c.prob.8.1.1': (
        r"""<p><b>Statement:</b> The two foundational limit theorems of probability describe complementary aspects of sample averages $\bar{X}_n = \frac{1}{n} \sum_{i=1}^n X_i$ for an iid sequence with finite mean $\mu$ and variance $\sigma^2$:"""
        r"""<br>(1) <b>Law of Large Numbers (LLN):</b> Establishes that the sample mean converges to the true population mean: $\bar{X}_n \to \mu$ (in probability for WLLN, almost surely for SLLN), demonstrating stability of long-run averages."""
        r"""<br>(2) <b>Central Limit Theorem (CLT):</b> Quantifies the magnitude and shape of fluctuations around the mean, showing that $\sqrt{n}(\bar{X}_n - \mu) = \frac{\sum X_i - n\mu}{\sigma \sqrt{n}} \xrightarrow{d} \mathcal{N}(0, 1)$ converges to a universal Gaussian bell curve.</p>"""
        r"""<p><b>Mathematical terms:</b> $\bar{X}_n$ is the sample mean; $\mu$ is the population mean; convergence in probability means $P(|\bar{X}_n - \mu| > \epsilon) \to 0$; almost sure convergence means $P(\lim \bar{X}_n = \mu) = 1$; $\xrightarrow{d}$ denotes convergence in distribution.</p>"""
        r"""<p><b>Reason:</b> As sample size $n$ increases, the variance of the average $\operatorname{Var}(\bar{X}_n) = \frac{\sigma^2}{n} \to 0$ collapses to zero, concentrating all probability mass at the point $\mu$ (the LLN). However, magnifying these microscopic deviations by the factor $\sqrt{n}$ balances the collapsing variance $\operatorname{Var}(\sqrt{n}(\bar{X}_n - \mu)) = n \frac{\sigma^2}{n} = \sigma^2$, revealing that the macroscopic distribution of random fluctuations is universally Gaussian regardless of the underlying distribution of the original variables.</p>"""
    ),
    'c.prob.8.2.1': (
        r"""<p><b>Statement:</b> Fundamental probability tail bounds:"""
        r"""<br>(1) <b>Markov's Inequality:</b> For any non-negative random variable $X \ge 0$ and any threshold $a > 0$:"""
        r"""$$P(X \ge a) \le \frac{E[X]}{a}$$"""
        r"""<br>(2) <b>Chebyshev's Inequality:</b> For any random variable $X$ with finite mean $\mu$ and finite variance $\sigma^2$, and any $k > 0$:"""
        r"""$$P(|X - \mu| \ge k) \le \frac{\sigma^2}{k^2}$$"""
        r"""Equivalently, setting $k = c\sigma$ for $c > 0$, $P(|X - \mu| \ge c\sigma) \le \frac{1}{c^2}$.</p>"""
        r"""<p><b>Mathematical terms:</b> $X \ge 0$ is non-negative; $a > 0$ is the tail threshold; $|X - \mu| \ge k$ is the deviation from the mean; $\sigma^2 = \operatorname{Var}(X)$ is variance; $k^2$ is the squared distance threshold.</p>"""
        r"""<p><b>Reason:</b> (1) For non-negative $X$, the step function $a \mathbf{1}_{\{X \ge a\}} \le X$ holds pointwise everywhere, because when $X < a$ the left side is 0, and when $X \ge a$ the left side is $a \le X$. Taking expectations preserves the inequality: $a E[\mathbf{1}_{\{X \ge a\}}] = a P(X \ge a) \le E[X]$. Dividing by $a > 0$ yields Markov's bound. (2) Define $Y = (X - \mu)^2 \ge 0$. Notice that $|X - \mu| \ge k \iff Y \ge k^2$. Applying Markov's inequality to $Y$ with threshold $k^2$ gives $P(Y \ge k^2) \le \frac{E[Y]}{k^2} = \frac{\operatorname{Var}(X)}{k^2} = \frac{\sigma^2}{k^2}$.</p>"""
    ),
    'c.prob.8.2.2': (
        r"""<p><b>Statement:</b> The <b>Weak Law of Large Numbers (WLLN)</b>: Let $X_1, X_2, \ldots$ be a sequence of uncorrelated (or independent) random variables with common mean $E[X_i] = \mu$ and bounded variance $\operatorname{Var}(X_i) \le \sigma^2 < \infty$. Define the sample average $\bar{X}_n = \frac{1}{n} \sum_{i=1}^n X_i$. Then for every $\epsilon > 0$:"""
        r"""$$\lim_{n \to \infty} P(|\bar{X}_n - \mu| \ge \epsilon) = 0$$"""
        r"""that is, the sample average $\bar{X}_n$ converges in probability to $\mu$ ($\bar{X}_n \xrightarrow{P} \mu$).</p>"""
        r"""<p><b>Mathematical terms:</b> $\bar{X}_n$ is the sample mean; $\epsilon > 0$ is any arbitrarily small tolerance threshold; convergence in probability means the probability of any non-zero estimation error vanishes as $n \to \infty$.</p>"""
        r"""<p><b>Reason:</b> By linearity of expectation, $E[\bar{X}_n] = \frac{1}{n}\sum E[X_i] = \mu$. Since the variables are uncorrelated, the variance of the average is $\operatorname{Var}(\bar{X}_n) = \frac{1}{n^2} \sum \operatorname{Var}(X_i) \le \frac{n\sigma^2}{n^2} = \frac{\sigma^2}{n}$. Applying Chebyshev's inequality to $\bar{X}_n$ with threshold $\epsilon > 0$ yields $P(|\bar{X}_n - \mu| \ge \epsilon) \le \frac{\operatorname{Var}(\bar{X}_n)}{\epsilon^2} \le \frac{\sigma^2}{n \epsilon^2}$. As $n \to \infty$, the upper bound $\frac{\sigma^2}{n\epsilon^2} \to 0$ for any fixed $\epsilon > 0$, forcing $P(|\bar{X}_n - \mu| \ge \epsilon) \to 0$ by the squeeze theorem.</p>"""
    ),
    'c.prob.8.3.1': (
        r"""<p><b>Statement:</b> The <b>Classical Central Limit Theorem (Lindeberg-Lévy CLT)</b>: Let $X_1, X_2, \ldots$ be an independent and identically distributed (iid) sequence of random variables with finite mean $\mu = E[X_i]$ and finite non-zero variance $\sigma^2 = \operatorname{Var}(X_i) > 0$. Define the partial sum $S_n = \sum_{i=1}^n X_i$ and sample mean $\bar{X}_n = S_n / n$. Then the standardized sum converges in distribution to the standard normal distribution:"""
        r"""$$Z_n = \frac{S_n - n\mu}{\sigma \sqrt{n}} = \frac{\bar{X}_n - \mu}{\sigma / \sqrt{n}} \xrightarrow{d} \mathcal{N}(0, 1)$$"""
        r"""meaning that for every $z \in \mathbb{R}$, $\lim_{n \to \infty} P(Z_n \le z) = \Phi(z) = \frac{1}{\sqrt{2\pi}} \int_{-\infty}^z e^{-t^2/2} \, dt$.</p>"""
        r"""<p><b>Mathematical terms:</b> $S_n$ is the sum of $n$ iid terms; $n\mu$ is the expected sum; $\sigma\sqrt{n}$ is the standard deviation of the sum; $\Phi(z)$ is the standard normal cumulative distribution function; $\xrightarrow{d}$ denotes convergence in distribution.</p>"""
        r"""<p><b>Reason:</b> Let $Y_i = \frac{X_i - \mu}{\sigma}$, so $E[Y_i] = 0$ and $\operatorname{Var}(Y_i) = 1$. The standardized sum is $Z_n = \frac{1}{\sqrt{n}} \sum_{i=1}^n Y_i$. Its characteristic function is $\phi_{Z_n}(t) = \left[\phi_Y\left(\frac{t}{\sqrt{n}}\right)\right]^n$. Expand $\phi_Y(u)$ in a Taylor series around $u = 0$: $\phi_Y(u) = 1 + i u E[Y] - \frac{u^2}{2} E[Y^2] + o(u^2) = 1 - \frac{u^2}{2} + o(u^2)$. Substituting $u = t/\sqrt{n}$ gives $\phi_{Z_n}(t) = \left(1 - \frac{t^2}{2n} + o\left(\frac{t^2}{n}\right)\right)^n$. As $n \to \infty$, this limit is well known: $\lim_{n \to \infty} (1 - \frac{t^2/2}{n})^n = e^{-t^2/2}$, which is the characteristic function of $\mathcal{N}(0, 1)$. By Lévy's Continuity Theorem, convergence of characteristic functions implies convergence in distribution.</p>"""
    ),
    'c.prob.8.3.2': (
        r"""<p><b>Statement:</b> Practical implementation of the Central Limit Theorem: for sufficiently large sample size (typically $n \ge 30$), the partial sum $S_n = \sum_{i=1}^n X_i$ of iid variables with mean $\mu$ and variance $\sigma^2$ is approximately normal $S_n \approx \mathcal{N}(n\mu, n\sigma^2)$, and the sample mean is approximately normal $\bar{X}_n \approx \mathcal{N}(\mu, \sigma^2/n)$. For any thresholds $a < b$:"""
        r"""$$P(a \le S_n \le b) \approx \Phi\left(\frac{b - n\mu}{\sigma \sqrt{n}}\right) - \Phi\left(\frac{a - n\mu}{\sigma \sqrt{n}}\right)$$</p>"""
        r"""<p>For integer-valued discrete sums, applying continuity correction replaces $a$ with $a - 0.5$ and $b$ with $b + 0.5$.</p>"""
        r"""<p><b>Mathematical terms:</b> $n\mu$ is the center of the sum; $\sigma\sqrt{n}$ is the standard error of the sum; $\sigma/\sqrt{n}$ is the standard error of the sample mean; $\Phi(\cdot)$ evaluates standard normal probabilities.</p>"""
        r"""<p><b>Reason:</b> Standardizing the event $\{a \le S_n \le b\}$ subtracts the expected value $n\mu$ and divides by the standard deviation $\sigma\sqrt{n}$ across all terms: $P\left(\frac{a - n\mu}{\sigma\sqrt{n}} \le \frac{S_n - n\mu}{\sigma\sqrt{n}} \le \frac{b - n\mu}{\sigma\sqrt{n}}\right)$. By the CLT, the standardized variable $Z_n$ is approximately $\mathcal{N}(0, 1)$, so the probability is given by the difference of standard normal CDF values $\Phi(z_{\text{upper}}) - \Phi(z_{\text{lower}})$.</p>"""
    ),
    'c.prob.8.4.1': (
        r"""<p><b>Statement:</b> The <b>Strong Law of Large Numbers (SLLN)</b>: Let $X_1, X_2, \ldots$ be a sequence of independent and identically distributed random variables with finite mean $E[|X_1|] < \infty$ and $\mu = E[X_1]$. Define the sample average $\bar{X}_n = \frac{1}{n} \sum_{i=1}^n X_i$. Then $\bar{X}_n$ converges to $\mu$ <b>almost surely</b> (with probability 1):"""
        r"""$$P\left(\lim_{n \to \infty} \bar{X}_n = \mu\right) = 1$$"""
        r"""Unlike the WLLN, which bounds the probability of error at a fixed sample size $n$, the SLLN asserts that with probability 1, the entire infinite trajectory $\bar{X}_n(\omega)$ converges to $\mu$.</p>"""
        r"""<p><b>Mathematical terms:</b> Almost sure convergence ($X_n \xrightarrow{a.s.} \mu$); $P(\lim \bar{X}_n = \mu) = 1$ means the event where the sample average fails to converge has probability zero; finite absolute expectation $E[|X|] < \infty$ is a necessary and sufficient condition.</p>"""
        r"""<p><b>Reason:</b> When fourth moments exist ($E[X^4] < \infty$), expand $E[(\bar{X}_n - \mu)^4] = \frac{1}{n^4} E[(\sum (X_i - \mu))^4] = \frac{1}{n^4} [n E[(X_1-\mu)^4] + 3n(n-1)\sigma^4] = O(1/n^2)$. By Markov's inequality, $P(|\bar{X}_n - \mu| > \epsilon) \le \frac{E[(\bar{X}_n - \mu)^4]}{\epsilon^4} \le \frac{C}{n^2 \epsilon^4}$. Because the $p$-series $\sum_{n=1}^\infty \frac{1}{n^2} < \infty$ converges, the Borel-Cantelli Lemma implies that the event $\{|\bar{X}_n - \mu| > \epsilon\}$ occurs for infinitely many $n$ with probability 0. In the general case where only $E[|X|] < \infty$, truncation and Kolmogorov's inequality establish almost sure convergence.</p>"""
    ),
    'c.prob.8.5.1': (
        r"""<p><b>Statement:</b> <b>Cantelli's Inequality (One-Sided Chebyshev Inequality):</b> Let $X$ be a random variable with mean $\mu$ and finite variance $\sigma^2$. Then for any $k > 0$, the probability of an extreme deviation in a single specified direction is bounded by:"""
        r"""$$P(X - \mu \ge k) \le \frac{\sigma^2}{\sigma^2 + k^2}$$"""
        r"""and symmetrically, $P(X - \mu \le -k) \le \frac{\sigma^2}{\sigma^2 + k^2}$. This bound strictly improves the two-sided Chebyshev bound $\frac{\sigma^2}{k^2}$ whenever $k > 0$.</p>"""
        r"""<p><b>Mathematical terms:</b> $k > 0$ is a positive deviation; $\frac{\sigma^2}{\sigma^2 + k^2} < \frac{\sigma^2}{k^2}$ is the one-sided bound; optimal parameter shift $c = \frac{\sigma^2}{k}$.</p>"""
        r"""<p><b>Reason:</b> For any real constant $c > 0$, notice $X - \mu \ge k \iff (X - \mu + c) \ge (k + c) > 0$. Therefore, $\{X - \mu \ge k\} \subseteq \{(X - \mu + c)^2 \ge (k + c)^2\}$. Applying Markov's inequality to the non-negative variable $(X - \mu + c)^2$ gives $P(X - \mu \ge k) \le \frac{E[(X - \mu + c)^2]}{(k + c)^2} = \frac{\sigma^2 + c^2}{(k + c)^2}$. Minimizing this function of $c$ by differentiating yields the optimal value $c^* = \sigma^2/k$. Substituting $c^*$ into the bound gives $\frac{\sigma^2 + (\sigma^2/k)^2}{(k + \sigma^2/k)^2} = \frac{\sigma^2(1 + \sigma^2/k^2)}{(k^2 + \sigma^2)^2/k^2} = \frac{\sigma^2}{k^2 + \sigma^2}$.</p>"""
    ),
    'c.prob.8.5.2': (
        r"""<p><b>Statement:</b> <b>Chernoff Bounds:</b> Let $X$ be a random variable with moment generating function $M_X(t) = E[e^{tX}]$ defined for $t > 0$. For any threshold $a \in \mathbb{R}$, the tail probability is bounded by minimizing the exponential Markov bound:"""
        r"""$$P(X \ge a) \le \inf_{t > 0} e^{-ta} M_X(t) = \exp\left(-\sup_{t > 0} [ta - \ln M_X(t)]\right)$$</p>"""
        r"""<p>where $I(a) = \sup_{t > 0} [ta - \ln M_X(t)]$ is the <b>Fenchel-Legendre transform</b> (rate function) of $X$, providing exponentially decaying bounds on large deviations.</p>"""
        r"""<p><b>Mathematical terms:</b> $M_X(t) = E[e^{tX}]$ is the MGF; $t > 0$ is a free tuning parameter; $\inf_{t > 0}$ is the infimum over all positive $t$; $\ln M_X(t)$ is the cumulant generating function; $I(a)$ is the large deviation rate function.</p>"""
        r"""<p><b>Reason:</b> Because $t > 0$, the exponential function is strictly increasing, so the event $\{X \ge a\}$ is logically identical to $\{e^{tX} \ge e^{ta}\}$. Because $e^{tX} > 0$ is strictly positive, applying Markov's inequality yields $P(X \ge a) = P(e^{tX} \ge e^{ta}) \le \frac{E[e^{tX}]}{e^{ta}} = e^{-ta} M_X(t)$. Because this inequality holds for every valid choice of $t > 0$, taking the infimum over all $t > 0$ yields the tightest possible upper bound, which decays exponentially fast in the distance of $a$ from the mean.</p>"""
    ),
    'c.prob.8.5.3': (
        r"""<p><b>Statement:</b> <b>Jensen's Inequality:</b> Let $X$ be an integrable random variable, and let $g: \mathbb{R} \to \mathbb{R}$ be a <b>convex function</b> (i.e. $g(\lambda x + (1-\lambda)y) \le \lambda g(x) + (1-\lambda)g(y)$ for all $\lambda \in [0, 1]$). If $E[X]$ and $E[g(X)]$ exist, then:"""
        r"""$$g(E[X]) \le E[g(X)]$$"""
        r"""If $g$ is concave, the inequality reverses: $g(E[X]) \ge E[g(X)]$. Strict inequality holds if $g$ is strictly convex and $X$ is not almost surely constant.</p>"""
        r"""<p><b>Mathematical terms:</b> Convex function $g$ (tangents lie below the graph); concave function (tangents lie above); $g(E[X])$ is the function evaluated at the mean; $E[g(X)]$ is the expected transformed value.</p>"""
        r"""<p><b>Reason:</b> Because $g$ is convex, at the point $\mu = E[X]$ there exists a sub-gradient (supporting tangent line) $L(x) = g(\mu) + c(x - \mu)$ such that $g(x) \ge L(x)$ for all $x \in \mathbb{R}$. Replacing $x$ by the random variable $X$ gives the inequality $g(X) \ge g(\mu) + c(X - \mu)$ almost surely. Taking expectations of both sides preserves the inequality by monotonicity of expectation: $E[g(X)] \ge E[g(\mu) + c(X - \mu)] = g(\mu) + c(E[X] - \mu) = g(E[X]) + c(0) = g(E[X])$.</p>"""
    ),
    'c.prob.8.5.4': (
        r"""<p><b>Statement:</b> Let $Y \sim \operatorname{NegBin}(r, p_n)$ be the number of failures before achieving $r$ successes in independent Bernoulli trials. If $r \to \infty$ and failure probability $q_n = 1 - p_n \to 0$ such that $r q_n \to \lambda > 0$, then the distribution of failures converges to a <b>Poisson distribution</b>:"""
        r"""$$Y \xrightarrow{d} \operatorname{Poisson}(\lambda)$$ pointwise for every $k \in \{0, 1, 2, \ldots\}$.</p>"""
        r"""<p><b>Mathematical terms:</b> $r$ is the success target; $q_n = 1 - p_n$ is the small failure probability; $r q_n \to \lambda$ is the expected failure total; convergence in distribution to $\operatorname{Poisson}(\lambda)$.</p>"""
        r"""<p><b>Reason:</b> Write the Negative Binomial PMF for failures: $P(Y = k) = \binom{k + r - 1}{k} p_n^r (1 - p_n)^k = \frac{(r + k - 1)\cdots r}{k!} (1 - q_n)^r q_n^k$. Substitute $q_n = \lambda/r$: the product $(r + k - 1)\cdots r \approx r^k$, which cancels the denominator of $q_n^k = \frac{\lambda^k}{r^k}$, leaving $\frac{\lambda^k}{k!}$. Furthermore, $(1 - q_n)^r = (1 - \frac{\lambda}{r})^r \to e^{-\lambda}$ as $r \to \infty$. Combining these limits yields $\lim_{r \to \infty} P(Y = k) = e^{-\lambda} \frac{\lambda^k}{k!}$, matching the Poisson PMF.</p>"""
    ),
    'c.prob.8.6.1': (
        r"""<p><b>Statement:</b> <b>Le Cam's Theorem (Poisson Approximation to Independent Bernoulli Sums):</b> Let $X_1, \ldots, X_n$ be independent Bernoulli random variables with success probabilities $P(X_i = 1) = p_i$. Define $S_n = \sum_{i=1}^n X_i$ and $\lambda = \sum_{i=1}^n p_i = E[S_n]$. Then the total variation distance between the distribution of $S_n$ and $\operatorname{Poisson}(\lambda)$ is bounded by:"""
        r"""$$d_{\mathrm{TV}}\left(\mathcal{L}(S_n), \, \operatorname{Poisson}(\lambda)\right) = \frac{1}{2} \sum_{k=0}^\infty |P(S_n = k) - e^{-\lambda} \frac{\lambda^k}{k!}| \le \sum_{i=1}^n p_i^2$$</p>"""
        r"""<p><b>Mathematical terms:</b> $d_{\mathrm{TV}}$ is total variation distance; $\mathcal{L}(S_n)$ is the law of the sum; $\lambda = \sum p_i$ is the total rate; $\sum p_i^2$ is the Le Cam error bound.</p>"""
        r"""<p><b>Reason:</b> Couple each Bernoulli variable $X_i$ with an independent Poisson variable $Y_i \sim \operatorname{Poisson}(p_i)$ on the same probability space such that $P(X_i \ne Y_i) \le p_i^2$. Because $\sum Y_i \sim \operatorname{Poisson}(\sum p_i) = \operatorname{Poisson}(\lambda)$, the total variation distance between the sums is bounded by the probability that the coupled sequences differ anywhere: $d_{\mathrm{TV}} \le P(\sum X_i \ne \sum Y_i) \le P(\bigcup \{X_i \ne Y_i\}) \le \sum_{i=1}^n P(X_i \ne Y_i) \le \sum_{i=1}^n p_i^2$. When all $p_i$ are small, $\sum p_i^2$ is negligible even if $n$ is large and the $p_i$ are unequal.</p>"""
    ),
    'c.prob.8.7.1': (
        r"""<p><b>Statement:</b> For a non-negative continuous random variable $X \ge 0$ (such as income or wealth) with CDF $F(x)$, finite mean $\mu = E[X] > 0$, and quantile function $Q(u) = F^{-1}(u)$ for $u \in [0, 1]$, the <b>Lorenz Curve</b> $L(u): [0, 1] \to [0, 1]$ represents the cumulative proportion of total population wealth possessed by the bottom $u$-quantile of the population:"""
        r"""$$L(u) = \frac{1}{\mu} \int_0^u Q(t) \, dt = \frac{\int_0^{F^{-1}(u)} x f(x) \, dx}{\int_0^\infty x f(x) \, dx}$$"""
        r"""The curve satisfies $L(0) = 0$, $L(1) = 1$, is convex ($L^{\prime\prime}(u) \ge 0$), and lies below the diagonal line of perfect equality $L(u) \le u$.</p>"""
        r"""<p><b>Mathematical terms:</b> $u \in [0, 1]$ is the population fraction; $Q(u) = F^{-1}(u)$ is the quantile; $L(u)$ is the cumulative share of total resources; $L(u) = u$ is the 45-degree line of perfect equality.</p>"""
        r"""<p><b>Reason:</b> By definition, $Q(t) = F^{-1}(t)$ is the wealth level of an individual at percentile $t$. Because $F^{-1}(t)$ is non-decreasing in $t$, integrating $F^{-1}(t)$ from 0 to $u$ sums the total wealth held by the poorest fraction $u$ of the population. Dividing by the total population wealth $\mu = \int_0^1 F^{-1}(t) dt$ scales the ratio to $[0, 1]$. Because $L^\prime(u) = \frac{F^{-1}(u)}{\mu}$ is non-decreasing, the second derivative $L^{\prime\prime}(u) \ge 0$, establishing that the Lorenz curve is convex and bows downward beneath the line of equality.</p>"""
    ),
    'c.prob.8.7.2': (
        r"""<p><b>Statement:</b> The <b>Gini Index</b> (Gini Coefficient) $G \in [0, 1]$ is defined as twice the area between the line of perfect equality ($L(u) = u$) and the Lorenz curve $L(u)$:"""
        r"""$$G = 2 \int_0^1 (u - L(u)) \, du = 1 - 2 \int_0^1 L(u) \, du$$"""
        r"""Equivalently, for independent copies $X_1, X_2 \overset{\text{iid}}{\sim} F$, $G$ equals half the relative mean absolute difference: $G = \frac{E[|X_1 - X_2|]}{2E[X_1]}$. A Gini coefficient of $0$ indicates perfect equality ($L(u) = u$), while $1$ indicates maximal inequality.</p>"""
        r"""<p><b>Mathematical terms:</b> $G \in [0, 1]$ is the Gini index; $\int_0^1 (u - L(u))du$ is the inequality gap area; $E[|X_1 - X_2|]$ is the mean absolute pairwise disparity.</p>"""
        r"""<p><b>Reason:</b> The total area under the diagonal of perfect equality on $[0, 1]$ is $\int_0^1 u du = 1/2$. The area between the diagonal and the Lorenz curve is $\int_0^1 (u - L(u)) du = 1/2 - \int_0^1 L(u) du$. Normalizing by the total area $1/2$ of the lower triangle scales the metric so that complete equality yields $G = \frac{1/2 - 1/2}{1/2} = 0$, while concentrated wealth yields $G \to 1$. By integrating $E[|X_1 - X_2|] = \iint |x_1 - x_2| dF(x_1)dF(x_2)$ by parts, it directly evaluates to $4\mu \int_0^1 (u - L(u)) du$, confirming that $G$ measures the average pairwise disparity scaled by the mean.</p>"""
    ),
}
